import Foundation

extension BusinessPlanDatabase {
    static let digitalPlans: [BusinessPlanData] = [
        BusinessPlanData(
            pathId: "web-design",
            mission: "Help small businesses establish and grow their online presence through professional, conversion-focused websites.",
            vision: "Build a web design agency serving local businesses with ongoing website management, SEO, and digital marketing services.",
            problemPoints: [
                "Most small businesses have outdated or no website, losing customers to competitors with better online presence.",
                "Business owners lack the technical skills to build or maintain their own sites.",
                "Affordable web design options often deliver templated, low-quality results."
            ],
            solutionPoints: [
                "Custom, professional websites designed specifically for the client's business and target customers.",
                "Mobile-responsive designs that work on all devices — critical since most searches are mobile.",
                "Ongoing maintenance and updates so the site stays current without the owner learning tech."
            ],
            primaryCustomer: "Local small business owners (restaurants, contractors, salons, professional services)",
            secondaryCustomer: "Startups, freelancers, and nonprofit organizations needing professional web presence",
            demographics: "Small business owners aged 30-60, revenue $100K–$2M, within local market or remote nationally",
            psychographics: "Know they need a website but overwhelmed by options, value someone who speaks plain English, want results not tech jargon",
            buyingMotivations: ["Starting a new business", "Current website is outdated or broken", "Not appearing in Google searches", "Losing customers to competitors with better websites"],
            serviceArea: "Local businesses in [Your City] plus remote clients nationwide",
            revenueStreams: ["Website design projects ($1,500–$5,000)", "Monthly maintenance plans ($100–$300/month)", "SEO setup and optimization ($500–$1,500)", "Content updates and blog management ($200–$500/month)", "Landing page and funnel design ($500–$2,000)"],
            upsells: ["Monthly SEO and content management", "Google Business Profile optimization", "Social media setup and management", "Email marketing integration", "E-commerce functionality"],
            pricingNotes: "Project-based pricing for initial builds. Monthly retainers for maintenance and SEO. Package tiers: Starter ($1,500), Professional ($3,000), Premium ($5,000+).",
            startupCostItemsEssential: [("Computer (if not already owned)", "$0–$1,000"), ("Domain and hosting for portfolio site", "$100–$200/year"), ("Design software (Figma free tier)", "$0"), ("Website builder platform (WordPress/Webflow)", "$0–$50/month")],
            startupCostItemsOptional: [("Premium themes and plugins", "$100–$300"), ("Stock photo subscription", "$100–$300/year"), ("Online course for skill building", "$50–$300"), ("Business cards", "$30–$50")],
            equipment: ["Computer with reliable internet", "Second monitor (productivity boost)", "Backup drive or cloud storage"],
            tools: ["Figma or Adobe XD for design", "WordPress or Webflow for development", "Elementor or Divi page builder", "Google Analytics", "PageSpeed Insights"],
            software: ["Figma (free tier)", "WordPress + hosting", "Google Workspace", "Stripe or PayPal for payments", "Trello or Notion for project management"],
            vehicleNeeds: "Not required. This is a fully remote-capable business. Local clients may appreciate occasional in-person meetings.",
            workspaceNeeds: "Home office with reliable internet and a quiet workspace for client calls. No storefront needed.",
            legalStructureRecommendation: "LLC recommended once you have regular clients. Protects personal assets from contract disputes.",
            licensesAndPermits: ["Business license", "No special permits required"],
            insuranceNeeds: ["Professional liability (errors and omissions)", "General liability (optional but recommended)"],
            operationsDaily: ["Check client messages and project updates", "Design and development work (core hours)", "Client calls and meetings", "Content updates for maintenance clients", "Invoicing and admin", "Learning and skill development"],
            schedulingWorkflow: "Project-based timelines: 2–4 weeks per website. Maintenance tasks batched weekly. Client meetings scheduled in blocks to protect design time.",
            customerWorkflow: "Inquiry → discovery call → proposal and quote → deposit and kickoff → design mockup → revisions → development → launch → maintenance plan offer",
            followUpWorkflow: "Post-launch check at 2 weeks. Monthly maintenance report. Quarterly SEO review. Annual redesign proposal.",
            marketingChannels: ["Portfolio website showcasing past work", "LinkedIn outreach to business owners", "Local business networking events", "Google Business Profile", "Referrals from existing clients"],
            acquisitionStrategies: ["Cold email local businesses with no website or outdated sites", "Offer free website audit to generate leads", "Attend local chamber of commerce events", "Partner with other service providers who serve small businesses"],
            referralStrategies: ["$200 referral fee for every client who signs a project", "Build relationships with complementary freelancers (copywriters, photographers)", "Ask every completed client for 2 referrals"],
            partnershipIdeas: ["Copywriters and content creators", "Photographers (product and headshot)", "SEO specialists", "Social media managers", "Print designers and brand agencies"],
            socialProofStrategies: ["Portfolio of live client websites", "Before/after website comparisons", "Client testimonials with revenue impact data", "Google reviews and LinkedIn recommendations"],
            salesProcess: ["Identify businesses with no website or poor websites", "Send personalized outreach highlighting specific improvements", "Offer free 15-minute audit call", "Present proposal with 2–3 package options", "Close with 50% deposit to start", "Deliver on time and upsell maintenance"],
            salesTips: ["Show, don't tell — mock up a quick homepage concept for the prospect", "Frame websites as revenue tools, not expenses", "Emphasize mobile-first design — show them their current site on a phone", "Monthly maintenance is where recurring revenue lives"],
            objectionHandling: [("I can build my own on Wix/Squarespace", "Those are great tools! But most business owners get stuck halfway through and the site never launches. I handle everything so you can focus on running your business."), ("Too expensive", "I understand. Consider that your website works 24/7 generating leads. Even one new client per month from your site pays for itself. I also have a starter package that fits smaller budgets.")],
            monthlyRevenueStarter: "$2,000–$4,000/month (1–2 projects + maintenance clients)",
            monthlyRevenueModerate: "$5,000–$8,000/month (2–3 projects + 10+ maintenance clients)",
            monthlyRevenueStrong: "$10,000–$20,000+/month (agency model with subcontractors)",
            estimatedMonthlyExpensesStarter: "$100–$300 (hosting, tools, software)",
            estimatedMonthlyExpensesModerate: "$500–$1,500 (add marketing, subcontractors, premium tools)",
            financialAssumptions: ["Average project: $2,500–$3,500", "Monthly maintenance: $150–$250/client", "Maintenance clients provide predictable recurring revenue", "1–2 new projects per month is sustainable for solo operator"],
            hiringPath: ["Solo for first year", "Subcontract development work for overflow", "Hire part-time designer or developer", "Project manager when running 5+ concurrent projects"],
            scalingPath: ["Build maintenance client base to 15–20 accounts", "Subcontract overflow work to other developers", "Add SEO and content services", "Transition to agency model with team"],
            expansionIdeas: ["SEO and content marketing services", "Social media management", "E-commerce development", "App development", "Brand identity and logo design"],
            riskFactors: ["Client acquisition is slow initially — persistence is key", "Scope creep on projects can kill profitability", "Technology changes require constant learning", "Competition from DIY website builders", "Payment delays from small business clients"],
            difficultyNotes: "Requires web design and basic development skills. Can be learned through structured online courses in 3–6 months. Portfolio is essential — build sample sites to start.",
            viabilityNotes: "Every business needs a website. Recurring maintenance revenue creates stability. Remote work capability means unlimited market reach. AI tools increase productivity but don't replace custom design.",
            launchSteps30Days: ["Build your own portfolio website", "Create 2–3 sample project case studies", "Set up Google Business Profile and LinkedIn", "Reach out to 20 local businesses without websites", "Complete first paid project (even at a discount)", "Collect first testimonial and case study"],
            launchSteps60Days: ["Complete 3–5 projects and build portfolio", "Launch maintenance plan offering", "Attend 2 local networking events", "Build referral relationships with complementary freelancers", "Reach 5+ Google reviews"],
            launchSteps90Days: ["Evaluate pricing and adjust based on demand", "Grow maintenance client base to 5–10", "Develop standardized project process and templates", "Assess need for subcontractors", "Set quarterly revenue targets"],
            fitSummary: "Website design is a high-demand, high-value digital service with excellent income potential and full remote capability. Monthly maintenance plans provide predictable recurring revenue.",
            bestFor: ["Creative and technical problem-solvers", "Those who enjoy helping businesses grow", "People seeking remote, flexible work", "Entrepreneurs building a scalable digital agency"]
        ),

        BusinessPlanData(
            pathId: "bookkeeping",
            mission: "Help small business owners stay organized, tax-ready, and financially informed through accurate, timely bookkeeping services.",
            vision: "Build a virtual bookkeeping practice serving small businesses nationwide with scalable systems and reliable recurring revenue.",
            problemPoints: [
                "Small business owners neglect bookkeeping until tax season creates a crisis.",
                "Hiring a full-time bookkeeper is too expensive for businesses under $1M revenue.",
                "DIY bookkeeping with QuickBooks leads to errors and missed deductions."
            ],
            solutionPoints: [
                "Monthly bookkeeping service that keeps books current and tax-ready year-round.",
                "Cloud-based systems so clients can see their numbers anytime.",
                "Plain-English financial reports that help owners make better business decisions."
            ],
            primaryCustomer: "Small business owners with $100K–$1M annual revenue",
            secondaryCustomer: "Freelancers, solopreneurs, real estate investors, and e-commerce sellers",
            demographics: "Business owners aged 25-55, solo or small team, service-based or e-commerce businesses",
            psychographics: "Know bookkeeping is important but find it overwhelming, want someone trustworthy to handle the numbers, value being tax-ready",
            buyingMotivations: ["Tax season panic — books are a mess", "Growing business that's outgrown DIY bookkeeping", "CPA recommended they get a bookkeeper", "Want to understand their financial position"],
            serviceArea: "Nationwide — fully remote service",
            revenueStreams: ["Monthly bookkeeping retainer ($300–$800/month)", "Catch-up bookkeeping ($500–$2,000)", "Payroll processing ($50–$150/month add-on)", "Tax preparation support ($200–$500/year)", "Financial reporting and advisory ($100–$300/month add-on)"],
            upsells: ["Payroll processing", "Accounts receivable management", "Bill pay services", "Monthly financial review calls", "Tax prep coordination with CPA"],
            pricingNotes: "Monthly retainers based on transaction volume. 0–100 transactions: $300–$400/month. 100–250: $400–$600. 250+: $600–$800+. Annual contracts with monthly billing.",
            startupCostItemsEssential: [("QuickBooks Online subscription", "$30–$80/month"), ("Bookkeeping certification (optional but recommended)", "$200–$500"), ("Computer with reliable internet", "$0–$1,000"), ("Professional liability insurance", "$300–$600/year")],
            startupCostItemsOptional: [("Additional software (Gusto, Dext)", "$20–$50/month each"), ("Website", "$200–$500"), ("Business cards", "$30–$50")],
            equipment: ["Computer with dual monitors (productivity)", "Reliable internet connection", "Headset for client calls"],
            tools: ["QuickBooks Online (primary)", "Xero (alternative)", "Dext or HubDoc for receipt management", "Excel/Google Sheets for reporting"],
            software: ["QuickBooks Online ProAdvisor", "Gusto or ADP for payroll", "Dext for document management", "Zoom for client meetings", "Practice management (Karbon or Jetpack Workflow)"],
            vehicleNeeds: "Not required. Fully remote business.",
            workspaceNeeds: "Home office with reliable internet, dual monitors, and quiet space for client calls.",
            legalStructureRecommendation: "LLC recommended. Handling client financial data creates liability exposure. Professional liability insurance also recommended.",
            licensesAndPermits: ["Business license", "No CPA license needed for bookkeeping (but don't call yourself an accountant)", "QuickBooks ProAdvisor certification (free, highly recommended)"],
            insuranceNeeds: ["Professional liability (errors and omissions)", "Cyber liability insurance (handling financial data)"],
            operationsDaily: ["Check client bank feeds and categorize transactions", "Reconcile accounts for clients on schedule", "Respond to client questions and requests", "Process invoices and bill payments", "Prepare monthly reports for clients due this week", "Follow up on outstanding client items"],
            schedulingWorkflow: "Monthly cycle: Week 1-2 close prior month books. Week 3 prepare and deliver reports. Week 4 client meetings and planning. Catch-up projects scheduled during lighter periods.",
            customerWorkflow: "Discovery call → proposal → engagement letter signed → onboarding (access to accounts) → initial cleanup → monthly recurring service → quarterly review calls",
            followUpWorkflow: "Monthly report delivery. Quarterly review call. Annual tax prep coordination. Year-end planning meeting in November.",
            marketingChannels: ["LinkedIn content and outreach", "Referrals from CPAs and tax preparers", "Facebook groups for small business owners", "Google Business Profile", "QuickBooks ProAdvisor directory"],
            acquisitionStrategies: ["Build relationships with 5–10 CPAs who can refer clients", "Post helpful bookkeeping tips on LinkedIn weekly", "Join Facebook groups for business owners and answer questions", "Offer free financial health assessment to generate leads"],
            referralStrategies: ["$100 referral fee to CPAs for each client signed", "Reciprocal referral agreement with CPAs", "Client referral discount ($50 off a month)"],
            partnershipIdeas: ["CPAs and tax preparers (primary referral source)", "Business coaches and consultants", "Payroll companies", "Business attorneys (new business formation clients need bookkeeping)"],
            socialProofStrategies: ["QuickBooks ProAdvisor certification badge", "Client testimonials about tax-readiness", "LinkedIn recommendations", "Case studies showing financial clarity improvements"],
            salesProcess: ["Discovery call to understand their business and pain points", "Assess current state of books", "Present proposal with clear scope and pricing", "Offer catch-up bookkeeping if needed", "Start with onboarding process", "Deliver consistent value monthly"],
            salesTips: ["Lead with the pain of tax season — everyone dreads it", "Emphasize that bookkeeping pays for itself in tax savings and better decisions", "CPAs are your best referral source — build those relationships first", "Offer a free initial assessment to demonstrate value"],
            objectionHandling: [("I do it myself in QuickBooks", "That's great that you're using QuickBooks! Many of my clients started that way. But are your books reconciled and tax-ready right now? I can take that off your plate so you can focus on growing your business."), ("Too expensive", "Consider what your time is worth. If bookkeeping takes you 10 hours/month and your time is worth $50/hour, you're spending $500 doing something I can do for less — and more accurately.")],
            monthlyRevenueStarter: "$1,500–$3,000/month (5–8 monthly clients)",
            monthlyRevenueModerate: "$4,000–$7,000/month (12–18 monthly clients)",
            monthlyRevenueStrong: "$8,000–$15,000+/month (20–30 clients, with add-on services)",
            estimatedMonthlyExpensesStarter: "$200–$400 (software, insurance, professional development)",
            estimatedMonthlyExpensesModerate: "$500–$1,000 (add marketing, additional software, subcontractors)",
            financialAssumptions: ["Average client: $400–$500/month", "Client retention: 85%+ annually", "Catch-up work adds $500–$2,000 per new client", "Tax season coordination adds $200–$500 per client annually"],
            hiringPath: ["Solo for first 15–20 clients", "Hire part-time bookkeeper for overflow", "Add senior bookkeeper for complex clients", "Operations manager at 30+ clients"],
            scalingPath: ["Build to 15–20 recurring clients", "Add payroll and advisory services", "Hire and train junior bookkeepers", "Develop niche specialization (e-commerce, contractors, etc.)"],
            expansionIdeas: ["Industry niche specialization", "CFO advisory services", "Tax preparation (with appropriate credentials)", "Bookkeeping training courses", "Payroll processing services"],
            riskFactors: ["Client acquisition takes time — recurring revenue builds slowly", "Handling client financial data creates liability", "Seasonal workload spikes during tax season", "Client businesses failing means lost accounts", "Keeping up with tax law and software changes"],
            difficultyNotes: "Moderate learning curve. QuickBooks ProAdvisor certification is free and highly valuable. Bookkeeping fundamentals can be learned in 2–3 months through online courses.",
            viabilityNotes: "Every small business needs bookkeeping. Fully remote, recurring revenue model. High client retention (85%+). Scales well with systems and team. Recession-resistant — businesses need bookkeeping regardless of economy.",
            launchSteps30Days: ["Complete QuickBooks ProAdvisor certification", "Set up LLC, insurance, and business banking", "Build simple website with services and pricing", "Reach out to 10 CPAs to introduce yourself", "Get first 2–3 clients (offer discount for first 3 months)", "Set up standardized onboarding process"],
            launchSteps60Days: ["Grow to 5–8 monthly clients", "Establish referral relationships with CPAs", "Join 3 online communities for small business owners", "Create monthly reporting template", "Start posting bookkeeping tips on LinkedIn"],
            launchSteps90Days: ["Evaluate client base and recurring revenue", "Refine onboarding and monthly workflow", "Add payroll service offering", "Plan for tax season support services", "Set annual client count and revenue targets"],
            fitSummary: "Bookkeeping is a high-demand, fully remote business with strong recurring revenue. Every small business needs it. CPA referral partnerships accelerate growth. Excellent work-life balance potential.",
            bestFor: ["Detail-oriented, organized individuals", "People who enjoy working with numbers", "Those seeking a fully remote, flexible business", "Anyone wanting predictable recurring monthly income"]
        ),

        BusinessPlanData(
            pathId: "social-media-management",
            mission: "Help small businesses grow their online presence and attract customers through strategic, consistent social media management.",
            vision: "Build a social media agency managing multiple client accounts with a team of content creators and strategists.",
            problemPoints: [
                "Small businesses know they need social media but lack the time, skills, or consistency to manage it.",
                "Posting randomly without strategy wastes time and produces no results.",
                "Hiring a full-time social media person is too expensive for most small businesses."
            ],
            solutionPoints: [
                "Done-for-you social media management with strategic content planning.",
                "Consistent posting schedule that builds audience and engagement over time.",
                "Monthly reporting showing growth and engagement metrics."
            ],
            primaryCustomer: "Local small businesses (restaurants, salons, fitness studios, retail)",
            secondaryCustomer: "Coaches, consultants, real estate agents, and personal brands",
            demographics: "Business owners aged 30-55, revenue $50K–$500K, active on Instagram/Facebook/TikTok",
            psychographics: "Know social media matters but overwhelmed by it, want results without spending hours creating content",
            buyingMotivations: ["Competitors are active on social media and getting attention", "No time to post consistently", "Previous attempts produced no results", "Want more local awareness and foot traffic"],
            serviceArea: "Local businesses and remote clients nationwide",
            revenueStreams: ["Monthly management retainer ($500–$2,000/month)", "Content creation packages ($300–$800/month)", "Social media setup and optimization ($200–$500 one-time)", "Paid advertising management ($300–$1,000/month + ad spend)", "Strategy consulting ($100–$200/hour)"],
            upsells: ["Paid ad campaign management", "Influencer outreach coordination", "Email marketing integration", "Video content creation", "Monthly analytics deep-dive reports"],
            pricingNotes: "Monthly retainers based on platforms and posting frequency. 3 posts/week on 2 platforms: $800–$1,200/month. 5 posts/week: $1,200–$2,000/month. Minimum 3-month commitment.",
            startupCostItemsEssential: [("Smartphone with good camera", "$0 (use existing)"), ("Canva Pro subscription", "$13/month"), ("Scheduling tool (Later, Buffer)", "$0–$25/month"), ("Portfolio website", "$100–$300")],
            startupCostItemsOptional: [("Adobe Creative Suite", "$55/month"), ("Stock photo subscription", "$10–$30/month"), ("Video editing software", "$0–$20/month"), ("Business cards", "$30–$50")],
            equipment: ["Smartphone with quality camera", "Ring light for content creation", "Tripod or phone mount", "Laptop for editing and scheduling"],
            tools: ["Canva for graphic design", "CapCut or InShot for video editing", "Later or Buffer for scheduling", "ChatGPT for caption drafts (edited for brand voice)"],
            software: ["Canva Pro", "Later or Buffer (scheduling)", "Google Analytics", "Meta Business Suite", "Google Sheets for reporting"],
            vehicleNeeds: "Not required. Remote service. Occasional travel for client photo/video shoots.",
            workspaceNeeds: "Home office. Good internet connection. Quiet space for client calls and content creation.",
            legalStructureRecommendation: "LLC optional initially. Recommended when managing ad budgets or working with 5+ clients.",
            licensesAndPermits: ["Business license", "No special permits required"],
            insuranceNeeds: ["Professional liability (errors and omissions)", "General liability (optional)"],
            operationsDaily: ["Check all client accounts for comments and messages", "Create and schedule content for the week", "Engage with followers on client accounts", "Monitor analytics and trending topics", "Client communication and approvals", "Content planning for upcoming campaigns"],
            schedulingWorkflow: "Batch content creation: spend 1–2 days/week creating content for all clients. Schedule posts in advance. Daily: monitor and engage on all accounts.",
            customerWorkflow: "Discovery call → audit current social media → proposal → onboarding (brand guidelines, access) → first month content plan → monthly reporting → quarterly strategy review",
            followUpWorkflow: "Weekly content approval cycle. Monthly performance report. Quarterly strategy call. Annual contract review.",
            marketingChannels: ["Your own social media accounts (practice what you preach)", "LinkedIn for B2B outreach", "Local networking events", "Referrals from existing clients", "Cold DM outreach to businesses with weak social presence"],
            acquisitionStrategies: ["DM local businesses with weak social media and offer a free audit", "Create case studies showing follower and engagement growth", "Post your own content consistently as proof of expertise", "Speak at local business events about social media strategy"],
            referralStrategies: ["$100 off monthly fee for every referral that signs", "Cross-refer with photographers, videographers, and web designers", "Ask clients for testimonials and introductions"],
            partnershipIdeas: ["Photographers and videographers (content creation)", "Web designers (bundled digital services)", "PR firms (social + PR packages)", "Business coaches (their clients need social media help)"],
            socialProofStrategies: ["Before/after follower and engagement statistics", "Client testimonials", "Your own social media following as proof", "Case studies with real metrics"],
            salesProcess: ["Identify businesses with poor social media presence", "Send DM or email with free audit offer", "Present audit findings and recommendations", "Propose monthly management package", "Start with 3-month commitment", "Deliver results and upsell additional services"],
            salesTips: ["Show them their competitors' social media — the gap motivates action", "Free audit is your best conversion tool", "Start with a small package and expand as they see results", "Monthly reports prove your value and justify the retainer"],
            objectionHandling: [("We post ourselves sometimes", "That's a great start! The challenge is consistency and strategy. Random posting doesn't build an audience. I create a strategic content plan that grows your following and drives real business results."), ("Social media doesn't work for our business", "I understand the skepticism. Let me show you 3 businesses in your industry that are getting real customers from social media. The difference is strategy and consistency.")],
            monthlyRevenueStarter: "$1,500–$3,000/month (3–4 clients)",
            monthlyRevenueModerate: "$4,000–$8,000/month (6–10 clients)",
            monthlyRevenueStrong: "$10,000–$20,000+/month (10–15 clients with ad management)",
            estimatedMonthlyExpensesStarter: "$100–$300 (software subscriptions, tools)",
            estimatedMonthlyExpensesModerate: "$500–$1,500 (add subcontractors, premium tools, marketing)",
            financialAssumptions: ["Average client: $800–$1,200/month", "Content creation time: 4–6 hours per client per month", "Can manage 8–12 clients solo", "Ad management adds $300–$1,000/month per client"],
            hiringPath: ["Solo for first 6–8 clients", "Hire part-time content creator", "Add community manager for engagement", "Account manager at 15+ clients"],
            scalingPath: ["Build to 8–10 clients as solo operator", "Systematize content creation with templates and batching", "Add paid ad management as premium service", "Hire team to scale beyond solo capacity"],
            expansionIdeas: ["Paid social media advertising management", "Influencer marketing coordination", "Social media training workshops", "Content creation studio", "TikTok and YouTube specialization"],
            riskFactors: ["Platform algorithm changes affect organic reach", "Client expectations may exceed realistic results", "Content creation burnout from managing many accounts", "Client churn if results take time", "Keeping up with rapidly changing social media trends"],
            difficultyNotes: "Low barrier to entry but requires creativity, consistency, and strategic thinking. Skills are developed through structured practice and online learning.",
            viabilityNotes: "Every business needs social media presence. Recurring monthly revenue model. Fully remote. Growing demand as social platforms become more important for local businesses.",
            launchSteps30Days: ["Build your own social media presence as a portfolio", "Create 3 case studies (even from your own accounts)", "Reach out to 20 local businesses with weak social presence", "Offer free social media audits to generate leads", "Sign first 2–3 clients", "Set up content creation and scheduling workflow"],
            launchSteps60Days: ["Grow to 4–6 clients", "Establish content batching system", "Begin posting results and case studies", "Join local business networking group", "Create monthly reporting template"],
            launchSteps90Days: ["Evaluate client satisfaction and retention", "Add paid ad management option", "Refine pricing based on workload", "Assess need for content creation help", "Set quarterly growth targets"],
            fitSummary: "Social media management is a high-demand, fully remote business with strong recurring revenue. Low startup cost and growing market demand. Scales well with systems and team.",
            bestFor: ["Creative people who understand social media platforms", "Those who enjoy content creation and storytelling", "People seeking a remote, flexible career", "Entrepreneurs interested in digital marketing"]
        ),

        BusinessPlanData(
            pathId: "tutoring",
            mission: "Help students build confidence and achieve academic success through personalized, patient tutoring.",
            vision: "Build a tutoring service that grows through results, referrals, and a team of qualified tutors serving the community.",
            problemPoints: [
                "Students falling behind in school need personalized attention that classrooms can't provide.",
                "Parents struggle to find patient, qualified tutors they can trust with their children.",
                "Test prep for SAT/ACT is stressful and generic prep courses don't address individual weaknesses."
            ],
            solutionPoints: [
                "One-on-one personalized tutoring tailored to each student's learning style and pace.",
                "Patient, encouraging approach that builds confidence alongside academic skills.",
                "Flexible scheduling — in-person at home or online via video call."
            ],
            primaryCustomer: "Parents of K-12 students struggling in specific subjects",
            secondaryCustomer: "High school students needing SAT/ACT prep, college students, adult learners",
            demographics: "Parents aged 30-50, household income $50K+, children in K-12, within local area or online nationally",
            psychographics: "Invested in their children's education, frustrated by falling grades, want trustworthy and effective help",
            buyingMotivations: ["Child's grades are declining", "Upcoming standardized tests (SAT, ACT)", "Learning gaps from pandemic schooling", "Gifted students wanting advanced work"],
            serviceArea: "In-person within 10 miles, online sessions available nationwide",
            revenueStreams: ["Individual tutoring sessions ($30–$75/hour)", "Weekly recurring packages ($120–$280/month for 4 sessions)", "SAT/ACT prep packages ($500–$1,500 for 10–20 sessions)", "Group tutoring sessions ($20–$40/student/hour)", "Summer intensive programs"],
            upsells: ["Test prep packages (SAT, ACT, AP exams)", "Summer learning programs", "Study skills and executive function coaching", "College application essay help", "Group sessions at reduced per-student rate"],
            pricingNotes: "Hourly rates by level: Elementary $30–$40, Middle School $35–$50, High School $40–$65, Test Prep $50–$75. Package discounts for 4+ sessions/month.",
            startupCostItemsEssential: [("Whiteboard and markers", "$20–$40"), ("Reference materials and workbooks", "$50–$100"), ("Laptop for online tutoring", "$0 (use existing)"), ("Zoom or Google Meet (free)", "$0")],
            startupCostItemsOptional: [("Tutoring platform subscription (Wyzant listing)", "$0 commission-based"), ("Website", "$100–$300"), ("Business cards and flyers", "$30–$50"), ("Educational apps/software", "$0–$50/month")],
            equipment: ["Laptop or tablet", "Whiteboard (portable or digital)", "Webcam and microphone for online sessions"],
            tools: ["Reference textbooks for key subjects", "Practice worksheets and problem sets", "Digital whiteboard (Miro, Jamboard)", "Timer for test prep practice"],
            software: ["Zoom or Google Meet", "Google Docs for shared notes", "Khan Academy (supplementary)", "Quizlet for flashcards"],
            vehicleNeeds: "Personal vehicle for in-home tutoring visits. Online tutoring requires no travel.",
            workspaceNeeds: "Home office for online sessions. In-person sessions at student's home or library. No storefront needed.",
            legalStructureRecommendation: "Sole proprietor is fine initially. LLC recommended if building a tutoring agency with multiple tutors.",
            licensesAndPermits: ["Business license", "Background check (parents may request this)"],
            insuranceNeeds: ["General liability (recommended when working with minors)"],
            operationsDaily: ["Prepare lesson plans for each student's session", "Conduct tutoring sessions (3–6 per day)", "Track student progress and update parents", "Respond to new inquiries", "Create practice materials", "Schedule upcoming sessions"],
            schedulingWorkflow: "Fixed weekly slots for recurring students. After-school hours (3pm–7pm) and weekends are peak. Online sessions can extend availability.",
            customerWorkflow: "Parent inquiry → free assessment session → discuss goals and plan → schedule recurring sessions → weekly sessions → monthly progress report → adjust as needed",
            followUpWorkflow: "Brief parent update after each session. Monthly progress summary. Report card season outreach. Summer program promotion in April/May.",
            marketingChannels: ["Parent Facebook groups", "Nextdoor", "School bulletin boards and parent newsletters", "Wyzant and Tutor.com profiles", "Word of mouth from satisfied parents"],
            acquisitionStrategies: ["Offer free initial assessment session", "Post in parent Facebook groups and Nextdoor", "Partner with after-school programs", "Distribute flyers at schools and libraries", "List on tutoring platforms for initial clients"],
            referralStrategies: ["Free session for every referred student who signs up", "Ask parents to share your info with other parents", "Partner with schools for recommended tutor list"],
            partnershipIdeas: ["After-school programs and learning centers", "Schools and teachers (unofficial referral)", "Child psychologists and educational therapists", "College prep counselors"],
            socialProofStrategies: ["Parent testimonials about grade improvements", "Before/after grade comparisons (with permission)", "Background check completion", "Subject expertise credentials"],
            salesProcess: ["Respond to parent inquiry within 2 hours", "Offer free 30-minute assessment", "Discuss student's challenges and create a plan", "Recommend session frequency and duration", "Start with weekly commitment", "Provide regular progress updates to parents"],
            salesTips: ["Parents buy results and trust — show both", "The free assessment is your best conversion tool", "Regular parent communication builds retention", "Specialize in 2–3 subjects rather than being a generalist"],
            objectionHandling: [("My kid won't cooperate with a tutor", "That's very common at first! I specialize in building rapport with students. The free assessment is low-pressure — let's see how it goes."), ("Too expensive", "I understand. Consider that one hour of focused tutoring can accomplish what hours of struggling alone cannot. I also offer package discounts that bring the per-session cost down.")],
            monthlyRevenueStarter: "$1,000–$2,000/month (part-time, 8–12 sessions/week)",
            monthlyRevenueModerate: "$3,000–$5,000/month (15–20 sessions/week)",
            monthlyRevenueStrong: "$6,000–$10,000+/month (with test prep packages and group sessions)",
            estimatedMonthlyExpensesStarter: "$50–$100 (materials, gas for travel)",
            estimatedMonthlyExpensesModerate: "$200–$400 (add marketing, software, materials)",
            financialAssumptions: ["Average session: $45–$55/hour", "Recurring students average 4–8 sessions/month", "Test prep packages: $750–$1,200 per student", "Retention: students stay 6–12 months on average"],
            hiringPath: ["Solo tutor for first year", "Add tutor for overflow subjects", "Build small tutoring team", "Administrative coordinator for scheduling"],
            scalingPath: ["Build recurring student base of 15–20 students", "Add SAT/ACT prep as premium offering", "Recruit additional tutors for subjects you don't cover", "Offer group sessions and workshops"],
            expansionIdeas: ["SAT/ACT/AP test prep specialization", "Online course creation", "Group workshops during school breaks", "Study skills and executive function coaching", "College application consulting"],
            riskFactors: ["Seasonal demand (drops in summer, peaks before exams)", "Student/parent expectations may be unrealistic about pace of improvement", "Scheduling challenges with after-school time slots", "Subject expertise limits who you can help", "Competition from online tutoring platforms"],
            difficultyNotes: "Low barrier to entry. Requires subject knowledge and patience. Teaching skill develops with practice. Background check recommended for credibility.",
            viabilityNotes: "Tutoring has consistent demand driven by concerned parents. Repeat business through the school year. Test prep is a high-value add-on. Can operate fully online.",
            launchSteps30Days: ["Identify your strongest 2–3 subjects", "Create profiles on Wyzant and Tutor.com", "Post in 5 local parent Facebook groups and Nextdoor", "Offer free assessment sessions to generate first students", "Complete first 5 paid sessions", "Collect parent testimonials"],
            launchSteps60Days: ["Build to 10–15 recurring sessions per week", "Create standard lesson plan templates", "Launch referral program for parents", "Begin monthly progress reporting", "Develop SAT/ACT prep offering"],
            launchSteps90Days: ["Evaluate student results and parent satisfaction", "Adjust pricing based on demand", "Expand subject offerings if qualified", "Plan for summer program or test prep intensive", "Set student count and revenue targets"],
            fitSummary: "Tutoring offers flexible, meaningful work with strong repeat business. Low startup cost, high hourly rates, and the satisfaction of helping students succeed.",
            bestFor: ["Patient, knowledgeable individuals who enjoy teaching", "Those seeking flexible part-time or full-time income", "People who find fulfillment in helping others learn", "Anyone with strong subject expertise wanting to monetize it"]
        )
    ]
}
