import Foundation

extension BusinessPlanDatabase {
    static let tradesPlans: [BusinessPlanData] = [
        BusinessPlanData(
            pathId: "electrician",
            mission: "Provide safe, code-compliant electrical services to residential and commercial customers with transparent pricing and reliable workmanship.",
            vision: "Build a trusted local electrical contracting business that grows through reputation, recurring maintenance contracts, and strategic hiring.",
            problemPoints: [
                "Homeowners and businesses struggle to find licensed electricians who show up on time and communicate clearly.",
                "Many existing providers are overbooked, overpriced, or deliver inconsistent quality.",
                "DIY electrical work creates safety hazards — customers need trustworthy professionals."
            ],
            solutionPoints: [
                "Licensed, insured electrical service with same-day or next-day availability for common jobs.",
                "Transparent flat-rate pricing — no surprise charges after the work is done.",
                "Clear communication from quote through completion, with photo documentation of all work."
            ],
            primaryCustomer: "Homeowners with properties 10+ years old needing upgrades, repairs, or panel work",
            secondaryCustomer: "Property managers, landlords, and small commercial tenants",
            demographics: "Homeowners aged 30-65, household income $60K+, within a 20-mile service radius",
            psychographics: "Value safety and compliance, willing to pay a premium for licensed and insured work, prefer local providers with reviews",
            buyingMotivations: ["Safety concerns with existing wiring", "Home renovation or remodel", "Code compliance for sale or insurance", "Adding circuits for modern appliances"],
            serviceArea: "[Your City] and surrounding communities within 20 miles",
            revenueStreams: ["Service calls and repairs ($150–$500)", "Panel upgrades ($1,500–$4,000)", "New construction and remodel wiring ($2,000–$10,000+)", "Recurring maintenance contracts ($200–$600/year)"],
            upsells: ["Whole-home surge protection", "Smart home wiring and automation", "Generator installation and transfer switches", "EV charger installation"],
            pricingNotes: "Flat-rate pricing for common jobs. Hourly rate of $75–$150/hr for custom work. Always provide written estimates before starting.",
            startupCostItemsEssential: [("Electrician license and bonding", "$500–$2,000"), ("Basic tool kit (multimeter, wire strippers, drill)", "$500–$1,000"), ("Vehicle (used van or truck)", "$5,000–$15,000"), ("Liability insurance", "$1,200–$2,500/year"), ("Initial material inventory", "$500–$1,000")],
            startupCostItemsOptional: [("Branded vehicle wrap", "$1,500–$3,000"), ("Website and online booking", "$500–$1,500"), ("Accounting software", "$20–$50/month")],
            equipment: ["Multimeter and circuit tester", "Wire strippers and crimpers", "Conduit bender", "Fish tape and glow rods", "Power drill and driver set"],
            tools: ["Voltage detector", "Wire nuts and connectors inventory", "Electrical tape and conduit fittings", "Panel covers and breakers", "Label maker for panel scheduling"],
            software: ["QuickBooks or Wave for invoicing", "Housecall Pro or Jobber for scheduling", "Google Business Profile for visibility"],
            vehicleNeeds: "Cargo van or pickup truck with organized tool storage. Essential for carrying materials and tools to job sites.",
            workspaceNeeds: "Home-based office for scheduling and admin. No storefront needed — all work is done at client locations.",
            legalStructureRecommendation: "LLC recommended. Protects personal assets from liability claims related to electrical work. Required by many states for licensed contractors.",
            licensesAndPermits: ["State or local electrician license (journeyman or master)", "Business license", "Contractor bond (varies by state)", "Building permits pulled per job as required"],
            insuranceNeeds: ["General liability insurance ($1M minimum)", "Workers compensation (required if hiring)", "Commercial auto insurance", "Tools and equipment coverage"],
            operationsDaily: ["Check schedule and confirm appointments", "Load vehicle with materials for the day's jobs", "Travel to job site, assess work, execute", "Document work with photos, update customer", "Invoice upon completion, collect payment", "Follow up within 48 hours for satisfaction check"],
            schedulingWorkflow: "Use Housecall Pro or Jobber to manage appointments. Offer 2-hour arrival windows. Send automated reminders 24 hours before appointments.",
            customerWorkflow: "Inquiry → phone assessment → on-site estimate → written quote → approval → schedule work → complete job → invoice → follow-up → request review",
            followUpWorkflow: "Text within 48 hours to confirm satisfaction. Email at 6 months for maintenance check. Annual reminder for panel inspection.",
            marketingChannels: ["Google Business Profile (critical for local search)", "Nextdoor and local Facebook groups", "Home Advisor and Angi leads", "Vehicle signage and yard signs at job sites", "Referral incentives for existing customers"],
            acquisitionStrategies: ["Offer free electrical safety inspections to generate leads", "Partner with real estate agents for pre-sale inspections", "Target property management companies for recurring contracts", "Run Google Local Service Ads for high-intent searches"],
            referralStrategies: ["$50 credit for every referred customer who books", "Leave business cards with every completed job", "Ask for Google reviews at job completion"],
            partnershipIdeas: ["Real estate agents (pre-listing inspections)", "General contractors (subcontract electrical)", "HVAC companies (cross-referral for panel upgrades)", "Solar installers (electrical tie-in work)"],
            socialProofStrategies: ["Before/after photos of panel upgrades", "Google review count prominently displayed", "Licensed and insured badge on all materials", "BBB accreditation if available"],
            salesProcess: ["Answer inquiry within 1 hour", "Ask qualifying questions (age of home, type of work)", "Schedule on-site estimate within 48 hours", "Provide written flat-rate quote on the spot", "Offer financing for jobs over $2,000", "Follow up within 24 hours if not booked immediately"],
            salesTips: ["Educate homeowners on safety — fear of electrical fires is a strong motivator", "Show your license and insurance proactively", "Offer a small discount for booking on the spot", "Always leave a quote even if they don't book immediately"],
            objectionHandling: [("Too expensive", "I understand. Keep in mind that licensed electrical work protects your home's value and your family's safety. Unlicensed work can void insurance claims and create fire hazards."), ("I'll get other quotes", "Absolutely — I encourage it. When comparing, make sure they're licensed, bonded, and insured. I'm happy to match any licensed competitor's written quote."), ("Can't I do it myself?", "Some small tasks are DIY-friendly, but anything involving your panel, new circuits, or 240V work requires a licensed electrician by code. I can handle the complex work and show you what's safe to do yourself.")],
            monthlyRevenueStarter: "$3,000–$5,000/month (solo, part-time, 2–3 jobs/week)",
            monthlyRevenueModerate: "$8,000–$12,000/month (solo, full-time, 5–8 jobs/week)",
            monthlyRevenueStrong: "$15,000–$25,000+/month (with 1–2 helpers, commercial contracts)",
            estimatedMonthlyExpensesStarter: "$800–$1,500 (insurance, gas, materials, phone)",
            estimatedMonthlyExpensesModerate: "$2,000–$4,000 (add vehicle payment, software, marketing)",
            financialAssumptions: ["Average service call revenue: $250–$400", "Average panel upgrade: $2,500", "Material costs typically 20–30% of job price", "Aim for 50%+ gross margin on all jobs"],
            hiringPath: ["Start solo to build reputation and cash flow", "Hire a helper/apprentice when booked 3+ weeks out", "Add a second licensed electrician to run a second truck", "Office admin when managing 10+ jobs/week"],
            scalingPath: ["Build recurring maintenance contract base", "Add a second service truck and technician", "Expand into commercial electrical work", "Offer specialty services (EV chargers, solar, smart home)"],
            expansionIdeas: ["EV charger installation (growing demand)", "Solar panel electrical tie-ins", "Smart home and automation wiring", "Emergency/after-hours service at premium rates"],
            riskFactors: ["Licensing requirements vary by state — research yours thoroughly", "Liability risk is real — always carry adequate insurance", "Seasonal slowdowns possible in some markets", "Material costs fluctuate — build margin into quotes", "Competition from established contractors — differentiate on service quality"],
            difficultyNotes: "Requires state licensing which takes 2–5 years of apprenticeship. High barrier to entry but this creates a competitive moat.",
            viabilityNotes: "Electricians are in critical shortage nationwide. Demand consistently exceeds supply. Strong long-term career with $75K–$100K+ earning potential.",
            launchSteps30Days: ["Verify license is current and all bonding/insurance is in place", "Set up LLC and business bank account", "Create Google Business Profile with photos of past work", "Order business cards and vehicle magnets", "Tell every contact you know that you're open for business", "Complete first 3–5 jobs and collect Google reviews"],
            launchSteps60Days: ["Launch targeted Google Local Service Ads", "Connect with 3 property managers for recurring work", "Reach out to 5 real estate agents for partnership", "Refine pricing based on market response", "Build a portfolio of before/after project photos"],
            launchSteps90Days: ["Evaluate revenue and adjust marketing spend", "Assess whether to hire a helper based on booking volume", "Establish relationships with electrical supply houses for contractor pricing", "Set up recurring maintenance contracts for existing clients", "Plan for specialty service expansion based on demand"],
            fitSummary: "Electrician is one of the highest-value skilled trades. Strong demand, high barriers to entry (licensing), and excellent income potential make this a top-tier career path for anyone willing to complete the required training.",
            bestFor: ["People who enjoy problem-solving and working with their hands", "Those willing to invest in apprenticeship and licensing", "Anyone seeking a recession-resistant career with high earning potential", "Entrepreneurs who want to eventually run their own contracting business"]
        ),

        BusinessPlanData(
            pathId: "plumber",
            mission: "Deliver reliable, honest plumbing services to residential and commercial customers with upfront pricing and quality workmanship.",
            vision: "Build a plumbing business known for integrity, fast response times, and customer loyalty that grows through referrals and recurring service agreements.",
            problemPoints: [
                "Plumbing emergencies create urgent demand — customers need fast, trustworthy service.",
                "Many plumbers have poor communication, hidden fees, and long wait times.",
                "Aging infrastructure means constant repair and replacement needs."
            ],
            solutionPoints: [
                "Licensed plumber with same-day emergency availability.",
                "Flat-rate pricing presented before work begins — no surprise bills.",
                "Professional communication with arrival windows and job status updates."
            ],
            primaryCustomer: "Homeowners with aging plumbing systems needing repairs, replacements, or upgrades",
            secondaryCustomer: "Property managers, landlords, restaurants, and small commercial tenants",
            demographics: "Homeowners aged 30-65, household income $50K+, properties 15+ years old",
            psychographics: "Frustrated by past plumbing experiences, value reliability and honesty, willing to pay fair prices for quality work",
            buyingMotivations: ["Emergency leaks and clogs", "Water heater failure", "Bathroom or kitchen remodel", "Preventive maintenance"],
            serviceArea: "[Your City] and surrounding areas within 25 miles",
            revenueStreams: ["Service calls and repairs ($150–$600)", "Water heater installation ($800–$2,500)", "Bathroom/kitchen rough-in ($2,000–$8,000)", "Drain cleaning ($150–$350)", "Maintenance agreements ($250–$500/year)"],
            upsells: ["Tankless water heater upgrade", "Whole-house water filtration", "Leak detection service", "Pipe insulation for winter"],
            pricingNotes: "Flat-rate pricing for standard repairs. Hourly rate of $85–$150 for complex custom work. Emergency after-hours rates at 1.5x standard.",
            startupCostItemsEssential: [("Plumbing license and bond", "$500–$2,000"), ("Professional tool set", "$1,000–$2,000"), ("Drain cleaning machine", "$500–$1,500"), ("Work vehicle", "$5,000–$15,000"), ("Liability insurance", "$1,200–$2,500/year")],
            startupCostItemsOptional: [("Vehicle wrap", "$1,500–$3,000"), ("Camera inspection equipment", "$2,000–$5,000"), ("Website", "$500–$1,500")],
            equipment: ["Pipe wrenches (multiple sizes)", "Drain auger/snake", "Pipe cutter and threading tools", "Soldering torch", "Camera inspection system"],
            tools: ["Basin wrench", "Teflon tape and pipe dope", "PEX crimping tools", "Hacksaw and tubing cutter", "Plungers and closet auger"],
            software: ["ServiceTitan or Housecall Pro", "QuickBooks for accounting", "Google Business Profile"],
            vehicleNeeds: "Cargo van or service body truck with organized compartments for fittings, tools, and a drain machine.",
            workspaceNeeds: "Home-based operations. No storefront needed. Garage or shed for material storage.",
            legalStructureRecommendation: "LLC strongly recommended. Plumbing work carries liability risk from water damage. LLC protects personal assets.",
            licensesAndPermits: ["State or local plumber license (journeyman or master)", "Business license", "Contractor bond", "Permits pulled per job as required by code"],
            insuranceNeeds: ["General liability ($1M minimum)", "Professional liability", "Commercial auto", "Workers compensation (if hiring)"],
            operationsDaily: ["Review and confirm daily schedule", "Stock vehicle with common parts and fittings", "Complete scheduled service calls", "Document all work with photos", "Invoice and collect payment on-site", "Follow up with previous customers"],
            schedulingWorkflow: "Use scheduling software with automated reminders. Reserve 1–2 slots daily for emergency calls. Offer 2-hour arrival windows.",
            customerWorkflow: "Call/text inquiry → phone diagnosis → dispatch or schedule → on-site assessment → written quote → approval → complete work → invoice → review request",
            followUpWorkflow: "Same-day text confirming work complete. 30-day check-in. 6-month maintenance reminder. Annual water heater flush reminder.",
            marketingChannels: ["Google Business Profile and Google Local Service Ads", "Nextdoor recommendations", "Home Advisor / Angi", "Vehicle signage", "Referral program"],
            acquisitionStrategies: ["Offer $49 drain clearing specials to generate first-time customers", "Partner with property managers for preferred vendor status", "Run seasonal campaigns (winterize pipes, water heater flush)", "Respond to emergency calls within 1 hour for premium positioning"],
            referralStrategies: ["$50 off next service for every referral that books", "Leave refrigerator magnets with phone number at every job", "Ask for Google reviews before leaving the job site"],
            partnershipIdeas: ["Real estate agents (pre-sale inspections)", "General contractors (subcontract plumbing)", "Water damage restoration companies (cross-referral)", "HVAC companies (bundled home maintenance)"],
            socialProofStrategies: ["Licensed and bonded badges on all marketing", "Google review count featured prominently", "Before/after photos of major jobs", "Customer testimonial videos"],
            salesProcess: ["Answer calls live or return within 15 minutes", "Diagnose over the phone when possible", "Arrive within quoted window", "Present flat-rate options (good/better/best)", "Complete work same visit when possible", "Collect payment and request review"],
            salesTips: ["Plumbing emergencies sell themselves — focus on speed and trust", "Offer good/better/best options to give the customer control", "Show your license and insurance without being asked", "Carry common parts to complete most repairs in one visit"],
            objectionHandling: [("Too expensive", "I understand. Here's what's included in that price: licensed work, warranty, and no hidden fees. Would you like to see a lower-cost option?"), ("I'll call someone else", "No problem. Make sure they're licensed and insured — unlicensed plumbing can cause major water damage issues down the road.")],
            monthlyRevenueStarter: "$3,000–$6,000/month (solo, 2–3 jobs/week)",
            monthlyRevenueModerate: "$8,000–$14,000/month (solo, full-time)",
            monthlyRevenueStrong: "$18,000–$30,000+/month (2+ trucks, commercial work)",
            estimatedMonthlyExpensesStarter: "$1,000–$2,000 (insurance, gas, parts, phone)",
            estimatedMonthlyExpensesModerate: "$3,000–$5,000 (vehicle, software, marketing, materials)",
            financialAssumptions: ["Average service call: $300–$500", "Average water heater install: $1,500", "Parts cost typically 15–25% of job price", "Target 55%+ gross margin"],
            hiringPath: ["Solo operation for first 6–12 months", "Hire apprentice when booked 3+ weeks out", "Add licensed plumber for second truck", "Admin hire when managing 15+ jobs/week"],
            scalingPath: ["Build recurring maintenance agreement base", "Add emergency/after-hours service at premium rates", "Expand into commercial plumbing", "Add specialty services (gas line, water treatment)"],
            expansionIdeas: ["Water treatment and filtration systems", "Gas line installation and repair", "Sewer line replacement (trenchless)", "Commercial kitchen plumbing"],
            riskFactors: ["Licensing requires 2–5 years of apprenticeship", "Water damage liability is significant — adequate insurance is critical", "Emergency calls can disrupt personal time", "Material costs and supply chain delays can impact margins", "Physical demands increase with age"],
            difficultyNotes: "Requires state licensing with years of apprenticeship. Physically demanding work. High barrier to entry creates strong competitive position.",
            viabilityNotes: "Critical shortage of plumbers nationwide. Average plumber earns $60K–$90K as an employee, $100K+ as an independent contractor. Demand is recession-resistant.",
            launchSteps30Days: ["Confirm license, bond, and insurance are current", "Register LLC and open business bank account", "Create Google Business Profile with service list", "Order business cards and vehicle magnets", "Complete 5+ jobs and collect reviews", "Set up invoicing and scheduling software"],
            launchSteps60Days: ["Launch Google Local Service Ads", "Contact 5 property management companies", "Partner with 3 real estate agents", "Build out seasonal marketing calendar", "Establish supplier accounts for contractor pricing"],
            launchSteps90Days: ["Evaluate marketing ROI and adjust spend", "Assess hiring needs based on booking volume", "Launch maintenance agreement program", "Add after-hours emergency service if demand supports it", "Plan specialty service expansion"],
            fitSummary: "Plumbing is one of the most in-demand and recession-proof skilled trades. Licensing creates a strong barrier to entry that protects your market position. Excellent income potential with clear scaling path.",
            bestFor: ["Hands-on problem solvers who enjoy physical work", "Those willing to complete apprenticeship training", "People seeking stable, high-income career with strong demand", "Future business owners looking for a scalable trade"]
        ),

        BusinessPlanData(
            pathId: "hvac",
            mission: "Provide expert heating, ventilation, and air conditioning services with honest diagnostics, transparent pricing, and lasting comfort solutions.",
            vision: "Become the go-to HVAC provider in our market through maintenance agreements, fast response times, and technical excellence.",
            problemPoints: [
                "HVAC failures happen at the worst times — extreme heat or cold creates urgent demand.",
                "Customers distrust HVAC companies that upsell unnecessary replacements.",
                "Many homes have aging systems that need maintenance or upgrades for efficiency."
            ],
            solutionPoints: [
                "Honest diagnostics — repair when possible, replace only when necessary.",
                "Flat-rate pricing with good/better/best options for every job.",
                "Priority service for maintenance agreement customers."
            ],
            primaryCustomer: "Homeowners with HVAC systems 8+ years old",
            secondaryCustomer: "Property managers, small commercial tenants, new construction builders",
            demographics: "Homeowners aged 30-70, household income $50K+, within 25-mile radius",
            psychographics: "Prioritize comfort and energy efficiency, frustrated by past HVAC experiences, value honest recommendations",
            buyingMotivations: ["System breakdown in extreme weather", "High energy bills", "Uneven heating/cooling", "New system installation for remodel or new build"],
            serviceArea: "[Your City] and surrounding communities within 25 miles",
            revenueStreams: ["Service calls and repairs ($150–$800)", "System installation ($5,000–$15,000)", "Maintenance agreements ($200–$400/year)", "Indoor air quality products ($500–$2,000)", "Duct cleaning and sealing ($300–$800)"],
            upsells: ["Smart thermostat installation", "UV air purification system", "Duct sealing and insulation", "Zoning systems for multi-story homes"],
            pricingNotes: "Flat-rate repair pricing. System installations quoted per job. Maintenance agreements provide recurring revenue and priority service positioning.",
            startupCostItemsEssential: [("HVAC license and EPA 608 certification", "$500–$1,500"), ("Professional tool set and gauges", "$1,500–$3,000"), ("Refrigerant recovery equipment", "$500–$1,000"), ("Work vehicle", "$5,000–$15,000"), ("Liability insurance", "$1,500–$3,000/year")],
            startupCostItemsOptional: [("Vehicle wrap", "$1,500–$3,000"), ("Combustion analyzer", "$500–$1,000"), ("Website and booking system", "$500–$1,500")],
            equipment: ["Manifold gauge set", "Refrigerant recovery machine", "Vacuum pump", "Combustion analyzer", "Multimeter and amp clamp"],
            tools: ["Tubing cutter and flaring tools", "Leak detector", "Temperature probes", "Duct tools and sheet metal shears", "Torque wrenches"],
            software: ["ServiceTitan or Housecall Pro", "QuickBooks", "Google Business Profile"],
            vehicleNeeds: "Cargo van or service body truck. Must carry refrigerant, recovery equipment, and standard replacement parts.",
            workspaceNeeds: "Home-based office. Garage or storage unit for parts inventory. No storefront required.",
            legalStructureRecommendation: "LLC strongly recommended. HVAC work involves refrigerant handling and gas connections — liability protection is essential.",
            licensesAndPermits: ["State HVAC contractor license", "EPA 608 Universal certification", "Business license", "Refrigerant handling certification"],
            insuranceNeeds: ["General liability ($1M minimum)", "Professional liability", "Commercial auto", "Workers compensation (when hiring)"],
            operationsDaily: ["Review schedule and confirm appointments", "Stock vehicle with common parts and refrigerant", "Complete service calls and installations", "Document work with photos and system data", "Invoice and collect payment", "Send maintenance reminders to due accounts"],
            schedulingWorkflow: "Scheduling software with automated reminders. Emergency slots reserved daily during peak seasons. 2-hour arrival windows for standard calls.",
            customerWorkflow: "Inquiry → phone triage → dispatch or schedule → on-site diagnosis → present options → approval → complete work → invoice → maintenance agreement offer → review request",
            followUpWorkflow: "Same-day completion text. 30-day satisfaction check. Seasonal maintenance reminders (spring AC, fall heating). Annual system check-up reminder.",
            marketingChannels: ["Google Business Profile and Local Service Ads", "Nextdoor and Facebook", "Home Advisor / Angi", "Vehicle branding", "Door hangers in neighborhoods after completing jobs"],
            acquisitionStrategies: ["$79 AC or furnace tune-up specials to generate leads", "Partner with home warranty companies", "Seasonal campaigns aligned with weather changes", "Fast emergency response as differentiator"],
            referralStrategies: ["$75 credit per referred customer who books", "Branded refrigerator magnets at every job", "Maintenance agreement discount for referrals"],
            partnershipIdeas: ["Real estate agents (pre-sale HVAC inspections)", "General contractors (new construction installs)", "Electricians (panel upgrades for HVAC systems)", "Plumbers (bundled home service agreements)"],
            socialProofStrategies: ["Manufacturer certifications displayed", "Google review volume", "Energy savings data from upgrades", "Licensed, bonded, insured messaging"],
            salesProcess: ["Respond to inquiries within 30 minutes", "Phone triage to assess urgency", "On-site diagnostic with clear explanation", "Present good/better/best options with pricing", "Offer financing for installations over $3,000", "Complete work and offer maintenance agreement"],
            salesTips: ["Lead with education — explain what's wrong and why in plain language", "Show energy cost savings for upgrades", "Offer maintenance agreements at every service call", "Emergency calls convert at very high rates — prioritize speed"],
            objectionHandling: [("Too expensive", "Let me show you the good/better/best options. The basic option handles the immediate issue. The premium option saves you money long-term on energy bills."), ("Is replacement really necessary?", "Let me walk you through the diagnosis. If repair is viable and cost-effective, I'll always recommend that first. Here's the repair-vs-replace comparison.")],
            monthlyRevenueStarter: "$4,000–$7,000/month (solo, part-time to full-time)",
            monthlyRevenueModerate: "$10,000–$18,000/month (solo, full-time with installations)",
            monthlyRevenueStrong: "$25,000–$50,000+/month (2–3 trucks, commercial contracts)",
            estimatedMonthlyExpensesStarter: "$1,200–$2,500 (insurance, gas, parts, refrigerant)",
            estimatedMonthlyExpensesModerate: "$3,500–$6,000 (vehicle, software, marketing, payroll)",
            financialAssumptions: ["Average service call: $300–$600", "Average installation: $7,000–$10,000", "Maintenance agreements: $300/year average with 80% renewal rate", "Material costs: 25–35% of installation price"],
            hiringPath: ["Solo for 6–12 months", "Hire apprentice/installer helper first", "Add second licensed technician", "Office coordinator when running 2+ trucks"],
            scalingPath: ["Build maintenance agreement base to 200+ customers", "Add installation crew separate from service", "Expand into commercial HVAC", "Offer indoor air quality as premium service line"],
            expansionIdeas: ["Commercial refrigeration", "Indoor air quality consulting", "Energy audits and efficiency upgrades", "Ductless mini-split specialization"],
            riskFactors: ["Licensing and EPA certification required", "Seasonal demand fluctuations (peak summer/winter)", "High-cost equipment investment for installations", "Refrigerant regulations and environmental compliance", "Competition from large national franchises"],
            difficultyNotes: "Requires HVAC license and EPA certification. Technical training through trade school or apprenticeship (1–4 years). Complex systems require ongoing education.",
            viabilityNotes: "HVAC technicians are in severe shortage. Average income $55K–$85K employed, $100K–$150K+ as independent contractors. Maintenance agreements create predictable recurring revenue.",
            launchSteps30Days: ["Verify all licenses, EPA certification, and insurance", "Set up LLC and business banking", "Create Google Business Profile", "Order vehicle signage and business cards", "Complete 5+ jobs and collect reviews", "Set up scheduling and invoicing software"],
            launchSteps60Days: ["Launch tune-up special marketing campaign", "Contact 5 property managers for service agreements", "Partner with 3 real estate agents", "Build seasonal marketing calendar", "Establish wholesale accounts with HVAC distributors"],
            launchSteps90Days: ["Evaluate marketing performance and ROI", "Launch maintenance agreement program", "Assess hiring needs based on demand", "Add indoor air quality services", "Plan for peak season staffing"],
            fitSummary: "HVAC is a top-tier skilled trade with massive demand, strong income potential, and excellent business scalability through maintenance agreements. Seasonal peaks create intense demand periods with premium pricing.",
            bestFor: ["Technical problem-solvers who enjoy mechanical systems", "Those willing to earn HVAC and EPA certifications", "People who want a high-demand, high-income trade", "Entrepreneurs planning to build a multi-truck service company"]
        ),

        BusinessPlanData(
            pathId: "welder",
            mission: "Provide precision welding and fabrication services for residential, commercial, and industrial clients with quality craftsmanship and reliable delivery.",
            vision: "Establish a welding business known for quality metalwork, expanding from repair services into custom fabrication and specialty welding.",
            problemPoints: [
                "Quality welders are increasingly scarce as experienced professionals retire.",
                "Customers struggle to find welders for small to medium jobs — most shops focus on large industrial contracts.",
                "Mobile welding for on-site repairs is in high demand but undersupplied."
            ],
            solutionPoints: [
                "Mobile welding service that comes to the customer's location.",
                "Handles jobs of all sizes — from fence repair to custom fabrication.",
                "Certified welds with quality guarantees and photo documentation."
            ],
            primaryCustomer: "Homeowners needing metal repairs, gates, fences, and railings",
            secondaryCustomer: "Farms, construction companies, auto shops, and small manufacturers",
            demographics: "Property owners, farmers, contractors, and small business owners within 30-mile radius",
            psychographics: "Need reliable metalwork, value quality and durability, often have urgent repair needs",
            buyingMotivations: ["Broken metal structures needing repair", "Custom gates, railings, or fences", "Farm and ranch equipment repair", "Industrial fabrication needs"],
            serviceArea: "[Your City] and surrounding areas within 30 miles",
            revenueStreams: ["Mobile welding repairs ($200–$800)", "Custom fabrication ($500–$5,000+)", "Structural welding ($1,000–$10,000+)", "Farm and equipment repair ($200–$2,000)"],
            upsells: ["Powder coating referral partnership", "Preventive maintenance inspections", "Custom design and CAD services", "Emergency mobile welding at premium rates"],
            pricingNotes: "Shop rate: $75–$125/hour. Mobile rate: $100–$175/hour plus travel fee. Custom fabrication quoted per project. Always provide written estimates.",
            startupCostItemsEssential: [("Welding certifications (AWS)", "$500–$1,500"), ("MIG and stick welder", "$1,000–$3,000"), ("Welding PPE and safety gear", "$300–$500"), ("Work truck with welding rig", "$8,000–$20,000"), ("Liability insurance", "$1,200–$2,500/year")],
            startupCostItemsOptional: [("TIG welder for specialty work", "$1,500–$3,000"), ("Plasma cutter", "$500–$1,500"), ("Shop space rental", "$500–$1,500/month")],
            equipment: ["MIG welder (wire feed)", "Stick welder (SMAW)", "Angle grinder", "Cutting torch (oxy-acetylene)", "Welding clamps and magnets"],
            tools: ["Chipping hammer and wire brush", "Measuring tools (tape, square, level)", "C-clamps and vise grips", "Metal file set", "Marking soapstone"],
            software: ["QuickBooks for invoicing", "Instagram for portfolio showcase", "Google Business Profile"],
            vehicleNeeds: "Flatbed truck or cargo trailer with mounted welding equipment, generator, and material storage. Essential for mobile welding operations.",
            workspaceNeeds: "Ideal: shop space with ventilation for fabrication work. Minimum: covered outdoor workspace for mobile prep. Many jobs are done on-site at the customer's location.",
            legalStructureRecommendation: "LLC recommended. Welding involves fire and structural liability risks. LLC protects personal assets.",
            licensesAndPermits: ["AWS welding certifications (recommended)", "Business license", "Contractor license (varies by state for structural work)"],
            insuranceNeeds: ["General liability ($1M minimum)", "Professional liability", "Commercial auto", "Tools and equipment coverage"],
            operationsDaily: ["Review job schedule and prepare materials", "Load truck with equipment and consumables", "Travel to job sites and complete work", "Document completed welds with photos", "Invoice and collect payment", "Follow up on pending estimates"],
            schedulingWorkflow: "Phone-based scheduling with confirmation texts. Book mobile jobs in geographic clusters to minimize travel time.",
            customerWorkflow: "Inquiry → on-site or photo assessment → written estimate → approval → schedule → complete work → inspect with customer → invoice → request review",
            followUpWorkflow: "Post-job quality check within one week. Quarterly follow-up for repeat commercial customers. Annual inspection offers for structural welds.",
            marketingChannels: ["Google Business Profile", "Instagram portfolio of completed work", "Facebook Marketplace and local groups", "Farm supply store bulletin boards", "Word of mouth and contractor referrals"],
            acquisitionStrategies: ["Build an Instagram portfolio with before/after welding photos", "Partner with auto shops and body shops for referral work", "Attend farm and ranch supply stores to network", "Offer free estimates for custom fabrication projects"],
            referralStrategies: ["10% discount for referrals from existing customers", "Business card with every completed job", "Cross-referral agreements with contractors"],
            partnershipIdeas: ["Auto body shops (frame and structural repair)", "General contractors (structural steel)", "Farm and ranch operations (equipment repair)", "Powder coating companies (finishing partnership)"],
            socialProofStrategies: ["AWS certification badges displayed", "Before/after portfolio on social media", "Customer testimonials with project photos", "Structural weld inspection documentation"],
            salesProcess: ["Respond to inquiry within 2 hours", "Assess job via photos or site visit", "Provide written estimate with scope of work", "Follow up within 48 hours if not booked", "Complete work to specification", "Request review and referral"],
            salesTips: ["Let your work portfolio sell for you — always photograph completed jobs", "Emphasize certification and quality for structural work", "Offer mobile convenience as a key differentiator", "Build relationships with repeat commercial customers"],
            objectionHandling: [("Too expensive", "Welding is specialized skilled work. The cost reflects certified quality that's safe and durable. I can adjust the scope to fit your budget if needed."), ("Can someone cheaper do it?", "Possibly, but check their certifications. Poor welds on structural work can be dangerous. My work comes with a quality guarantee.")],
            monthlyRevenueStarter: "$3,000–$5,000/month (part-time, mobile repairs)",
            monthlyRevenueModerate: "$7,000–$12,000/month (full-time, mixed repairs and fabrication)",
            monthlyRevenueStrong: "$15,000–$25,000+/month (with shop, helper, and commercial contracts)",
            estimatedMonthlyExpensesStarter: "$800–$1,500 (gas, consumables, insurance)",
            estimatedMonthlyExpensesModerate: "$2,500–$4,500 (shop rent, materials, vehicle, marketing)",
            financialAssumptions: ["Average mobile repair: $400–$600", "Average custom fabrication: $1,500–$3,000", "Consumables (wire, gas, rod) typically 10–15% of revenue", "Travel fees cover fuel costs for mobile work"],
            hiringPath: ["Solo operation for first year", "Hire helper/apprentice for heavy lifting and prep", "Add second certified welder for volume", "Shop manager when running a full fabrication shop"],
            scalingPath: ["Start with mobile repairs, add shop space for fabrication", "Build commercial and industrial client base", "Offer specialty welding (aluminum, stainless, TIG)", "Subcontract to larger construction projects"],
            expansionIdeas: ["Aluminum and stainless steel specialty welding", "Artistic and decorative metalwork", "Industrial pipe welding (pipeline work)", "Welding instruction and training"],
            riskFactors: ["Physical demands and safety hazards require strict PPE compliance", "Certification investment and ongoing training costs", "Material price fluctuations affect project margins", "Competition from large welding shops for industrial contracts", "Weather affects outdoor mobile welding operations"],
            difficultyNotes: "Requires welding training and certification (3–12 months for basic, longer for specialty). Physical work with safety considerations. Moderate barrier to entry.",
            viabilityNotes: "Massive welder shortage nationwide. Certified welders command premium rates. Mobile welding services are especially in demand in rural and suburban areas.",
            launchSteps30Days: ["Obtain or verify AWS certifications", "Set up LLC and business banking", "Equip mobile welding rig on truck", "Create Google Business Profile and Instagram portfolio", "Complete 5+ jobs and collect reviews", "Network with local contractors and auto shops"],
            launchSteps60Days: ["Build relationships with 3+ regular commercial clients", "Launch targeted social media marketing with portfolio", "Connect with farm and ranch supply networks", "Establish material supplier accounts", "Refine pricing based on market response"],
            launchSteps90Days: ["Evaluate shop space need based on fabrication demand", "Assess hiring needs", "Add specialty welding services if trained", "Plan for equipment upgrades", "Set revenue targets for next quarter"],
            fitSummary: "Welding combines skilled craftsmanship with strong market demand. Mobile welding services fill a critical gap. Excellent income potential with paths to shop ownership and specialty work.",
            bestFor: ["Hands-on workers who enjoy precision metalwork", "Those with welding training or willingness to get certified", "People who want a mobile, independent skilled trade", "Anyone interested in both repair work and creative fabrication"]
        ),

        BusinessPlanData(
            pathId: "diesel-mechanic",
            mission: "Keep commercial vehicles, heavy equipment, and diesel-powered machinery running reliably through expert diagnostics and repair.",
            vision: "Build a mobile diesel repair service that becomes the preferred provider for fleets, farms, and construction companies in the region.",
            problemPoints: [
                "Fleet operators lose thousands per day when trucks are down — they need fast, reliable repair.",
                "Most diesel shops have multi-day wait times for non-emergency work.",
                "Mobile diesel mechanics are scarce despite strong demand."
            ],
            solutionPoints: [
                "Mobile diesel repair that comes to the fleet yard or job site.",
                "Reduced downtime through fast diagnostics and common-repair parts inventory.",
                "Preventive maintenance programs that catch problems before breakdowns."
            ],
            primaryCustomer: "Fleet operators, trucking companies, and owner-operators",
            secondaryCustomer: "Construction companies, farms, and municipalities with diesel equipment",
            demographics: "Fleet managers and business owners within 40-mile service radius, operating 5+ diesel vehicles or heavy equipment",
            psychographics: "Downtime costs them money — they value speed and reliability over lowest price",
            buyingMotivations: ["Vehicle breakdown causing revenue loss", "DOT inspection compliance", "Preventive maintenance requirements", "Fleet cost reduction"],
            serviceArea: "[Your Region] — fleet yards, construction sites, and farm operations within 40 miles",
            revenueStreams: ["Mobile repair service calls ($200–$1,000+)", "Preventive maintenance contracts ($300–$800/vehicle/year)", "DOT inspection services ($100–$200)", "Engine and transmission overhaul ($3,000–$10,000+)"],
            upsells: ["Preventive maintenance agreements", "DOT compliance inspection packages", "Fleet reporting and maintenance tracking", "Emergency after-hours repair at premium rates"],
            pricingNotes: "Shop rate equivalent: $100–$150/hour. Mobile rate: $125–$175/hour plus travel. Fleet contracts priced per vehicle per year. Emergency rates at 1.5x–2x standard.",
            startupCostItemsEssential: [("Diesel diagnostic scan tools", "$2,000–$5,000"), ("Professional tool set", "$3,000–$8,000"), ("Service truck with crane/lift", "$15,000–$30,000"), ("Liability insurance", "$2,000–$4,000/year"), ("Common parts inventory", "$1,000–$3,000")],
            startupCostItemsOptional: [("ASE diesel certifications", "$500–$1,000"), ("Vehicle wrap", "$2,000–$3,500"), ("Website", "$500–$1,500")],
            equipment: ["Diesel diagnostic scanner", "Compression tester", "Fuel pressure tester", "Hydraulic jack and stands", "Impact wrench set"],
            tools: ["Socket sets (metric and SAE)", "Specialty diesel tools", "Torque wrenches", "Electrical testing equipment", "Fluid evacuation equipment"],
            software: ["Fleet management/tracking software", "QuickBooks", "Google Business Profile"],
            vehicleNeeds: "Heavy-duty service truck with crane, air compressor, and organized tool storage. This is your mobile shop — it's your biggest investment.",
            workspaceNeeds: "Home-based with large garage or shop for overflow work. Most jobs are performed on-site at client locations.",
            legalStructureRecommendation: "LLC recommended. Heavy equipment work involves significant liability. Commercial clients often require proof of LLC and insurance.",
            licensesAndPermits: ["ASE diesel certifications (recommended, often required by fleet clients)", "Business license", "EPA certifications for refrigerant/emissions work"],
            insuranceNeeds: ["General liability ($1M–$2M)", "Garage keeper's liability", "Commercial auto", "Tools and equipment coverage"],
            operationsDaily: ["Review service schedule and fleet PM calendar", "Stock truck with parts for scheduled work", "Travel to fleet yards and job sites", "Complete diagnostics and repairs", "Update fleet maintenance records", "Invoice and schedule next service"],
            schedulingWorkflow: "Fleet PMs scheduled weekly/monthly. Emergency calls prioritized. Geographic routing to minimize drive time between clients.",
            customerWorkflow: "Fleet contact calls with issue → phone diagnosis → dispatch → on-site repair → update fleet records → invoice → PM schedule setup",
            followUpWorkflow: "Same-day repair summary to fleet manager. Weekly PM schedule reminders. Monthly fleet health reports for contract clients.",
            marketingChannels: ["Direct outreach to fleet operators and trucking companies", "Google Business Profile", "Trucking industry forums and associations", "Trade shows and industry events", "Word of mouth in the fleet community"],
            acquisitionStrategies: ["Visit fleet yards in person to introduce services", "Offer free fleet inspection to win first contract", "Join local trucking and fleet associations", "Partner with parts suppliers for referrals"],
            referralStrategies: ["Referral bonus for fleet managers who introduce new clients", "Parts supplier partnership referrals", "Owner-operator network word of mouth"],
            partnershipIdeas: ["Diesel parts suppliers (mutual referrals)", "Trucking companies (preferred vendor agreements)", "Construction equipment dealers (overflow repair)", "Towing companies (breakdown referrals)"],
            socialProofStrategies: ["ASE certification badges", "Fleet client testimonials", "Uptime statistics for maintained fleets", "Before/after repair documentation"],
            salesProcess: ["Visit fleet yards to introduce services", "Offer free fleet inspection", "Present PM agreement proposal", "Demonstrate cost savings vs. dealer rates", "Start with one truck to prove quality", "Expand to full fleet contract"],
            salesTips: ["Speak the language of downtime cost — show how fast repair saves money", "Fleet managers care about reliability and documentation", "Start with one vehicle to prove yourself, then expand to the fleet", "Offer better pricing than dealer service departments"],
            objectionHandling: [("We use the dealer", "Dealers are great for warranty work. For everything else, I can save you 20-40% with faster turnaround because I come to you."), ("How do I know you're qualified?", "Here are my ASE certifications. I've worked on [X] brands/models for [Y] years. I can provide references from other fleet clients.")],
            monthlyRevenueStarter: "$4,000–$7,000/month (part-time, building client base)",
            monthlyRevenueModerate: "$10,000–$16,000/month (full-time, fleet contracts)",
            monthlyRevenueStrong: "$20,000–$40,000+/month (multiple fleet contracts, helper)",
            estimatedMonthlyExpensesStarter: "$1,500–$3,000 (fuel, parts, insurance, tools)",
            estimatedMonthlyExpensesModerate: "$4,000–$7,000 (truck payment, parts inventory, marketing)",
            financialAssumptions: ["Average service call: $400–$800", "Fleet PM per vehicle: $400–$600/year", "Parts markup: 20–30%", "Target 50%+ gross margin on labor"],
            hiringPath: ["Solo for first year", "Hire helper for heavy jobs", "Add second mechanic for second service truck", "Fleet coordinator for scheduling and admin"],
            scalingPath: ["Build fleet PM contract base", "Add second service truck and mechanic", "Expand into heavy equipment repair", "Offer emergency 24/7 service at premium rates"],
            expansionIdeas: ["Heavy equipment repair for construction", "DOT inspection station", "Diesel performance upgrades", "Fleet management consulting"],
            riskFactors: ["High initial equipment investment", "Physical demands of heavy equipment work", "Parts availability can delay repairs", "Fleet clients expect fast turnaround — reputation is everything", "Liability exposure from commercial vehicle work"],
            difficultyNotes: "Requires diesel mechanic training and preferably ASE certifications. High equipment investment. Technical complexity requires ongoing education.",
            viabilityNotes: "Severe shortage of diesel mechanics nationally. Fleet operators pay premium rates for reliable mobile service. Recession-resistant — trucks must run regardless of economy.",
            launchSteps30Days: ["Obtain or verify ASE diesel certifications", "Set up LLC, insurance, and business banking", "Equip service truck with tools and diagnostic equipment", "Visit 10 fleet yards to introduce services", "Complete first 5 jobs and collect testimonials", "Set up invoicing and fleet tracking system"],
            launchSteps60Days: ["Secure first fleet PM contract", "Build relationships with 3+ diesel parts suppliers", "Launch Google Business Profile", "Establish after-hours emergency availability", "Create monthly fleet reporting template"],
            launchSteps90Days: ["Evaluate fleet contract profitability", "Assess need for helper or second truck", "Expand outreach to construction and farm equipment", "Set quarterly revenue targets", "Plan for equipment upgrades based on demand"],
            fitSummary: "Diesel mechanics are in critical demand. Mobile service commands premium rates. Fleet contracts provide predictable recurring revenue. One of the strongest earning potentials in skilled trades.",
            bestFor: ["Mechanically inclined individuals who enjoy heavy equipment", "Those with diesel training or willingness to earn certifications", "People who want premium pay in a shortage field", "Independent operators building a fleet service business"]
        ),

        BusinessPlanData(
            pathId: "aircraft-mechanic",
            mission: "Ensure aircraft safety and airworthiness through expert maintenance, inspection, and repair of general aviation and commercial aircraft.",
            vision: "Become a trusted A&P mechanic serving general aviation aircraft owners and FBOs, with potential to open an independent maintenance facility.",
            problemPoints: [
                "Aircraft owners struggle to find available A&P mechanics — the workforce is aging and shrinking.",
                "FBOs and flight schools have long wait times for maintenance.",
                "Aircraft maintenance costs are high — owners want transparent, trustworthy mechanics."
            ],
            solutionPoints: [
                "FAA-licensed A&P mechanic providing thorough, documented maintenance and inspections.",
                "Flexible scheduling for annual inspections and routine maintenance.",
                "Clear communication and transparent pricing — no surprise findings without consultation."
            ],
            primaryCustomer: "General aviation aircraft owners (single and multi-engine piston)",
            secondaryCustomer: "Flight schools, FBOs, and small charter operators",
            demographics: "Aircraft owners aged 35-70, typically high net worth, within 50-mile radius of home airport",
            psychographics: "Safety-focused, value thorough and honest work, building long-term relationship with their mechanic",
            buyingMotivations: ["Annual inspection requirements (FAA-mandated)", "Squawk list items needing repair", "Pre-purchase inspections", "Avionics upgrades"],
            serviceArea: "General aviation airports within 50 miles, with travel capability for on-field maintenance",
            revenueStreams: ["Annual inspections ($1,500–$5,000+)", "Hourly maintenance and repair ($85–$125/hr)", "Pre-purchase inspections ($500–$2,000)", "Avionics installation support ($500–$3,000+)"],
            upsells: ["Avionics upgrade consultation", "Corrosion prevention programs", "Engine monitoring system installation", "Aircraft detailing referral partnership"],
            pricingNotes: "Hourly rate: $85–$125/hour. Annual inspections billed hourly plus parts. Pre-purchase inspections flat rate. All work documented per FAA requirements.",
            startupCostItemsEssential: [("A&P license (requires FAA-approved training)", "$15,000–$30,000 for school"), ("Aviation tool set", "$3,000–$8,000"), ("Liability insurance (aviation-specific)", "$2,000–$5,000/year"), ("FAA inspection authorization (IA) if applicable", "$500–$1,000"), ("Reference materials and manuals", "$500–$1,000")],
            startupCostItemsOptional: [("Hangar or shop space at airport", "$500–$2,000/month"), ("Specialized tooling for specific aircraft types", "$1,000–$5,000"), ("Vehicle for airport-to-airport travel", "$5,000–$15,000")],
            equipment: ["Aviation-grade hand tools", "Compression tester", "Borescope", "Torque wrenches (calibrated)", "Safety wire pliers"],
            tools: ["Aircraft jacks and stands", "Pitot-static test equipment", "Multimeter and avionics test equipment", "Rigging tools", "Log book and documentation supplies"],
            software: ["Aircraft maintenance tracking software", "QuickBooks for billing", "FAA regulatory reference database"],
            vehicleNeeds: "Reliable vehicle for traveling between airports. Some mechanics operate from a home base airport.",
            workspaceNeeds: "Hangar space at a local airport is ideal. Many A&P mechanics start by renting space or working at client aircraft locations.",
            legalStructureRecommendation: "LLC essential. Aviation maintenance carries significant liability. Aviation-specific insurance is required.",
            licensesAndPermits: ["FAA Airframe and Powerplant (A&P) certificate", "Inspection Authorization (IA) for annual inspections", "Business license", "Airport access credentials"],
            insuranceNeeds: ["Aviation maintenance liability insurance", "General liability", "Tools and equipment coverage", "Hangar keeper's liability (if renting hangar)"],
            operationsDaily: ["Review maintenance schedule and parts availability", "Perform inspections and maintenance per manufacturer manuals", "Document all work in aircraft logs per FAA requirements", "Communicate findings and recommendations to owners", "Order parts and coordinate with vendors", "Complete and sign off maintenance entries"],
            schedulingWorkflow: "Book annual inspections 2–4 weeks in advance. Routine maintenance scheduled weekly. Emergency AOG (aircraft on ground) prioritized.",
            customerWorkflow: "Owner contacts with maintenance need → schedule inspection → perform work per maintenance manual → document in logbooks → sign off → invoice → schedule next service",
            followUpWorkflow: "Post-maintenance follow-up within 1 week. Annual inspection reminder 60 days before due date. AD (Airworthiness Directive) compliance tracking for each client aircraft.",
            marketingChannels: ["Airport FBO bulletin boards", "Aviation forums and owner groups (Beechtalk, Cirrus Owners, etc.)", "EAA chapter meetings", "Direct relationships with aircraft owners at local airports", "Word of mouth in aviation community"],
            acquisitionStrategies: ["Introduce yourself at local FBOs and flight schools", "Attend EAA chapter meetings and fly-ins", "Offer competitive annual inspection pricing to build clientele", "Provide pre-purchase inspections for aircraft brokers"],
            referralStrategies: ["Referral discount on next annual inspection", "Build relationships with flight instructors who recommend mechanics", "Partner with avionics shops for cross-referrals"],
            partnershipIdeas: ["FBOs (on-field maintenance provider)", "Flight schools (fleet maintenance contracts)", "Aircraft brokers (pre-purchase inspections)", "Avionics shops (installation support)"],
            socialProofStrategies: ["FAA A&P and IA credentials prominently displayed", "Aircraft type experience list", "Owner testimonials", "Years of experience and aircraft maintained count"],
            salesProcess: ["Meet aircraft owners at the airport", "Discuss their aircraft and maintenance history", "Offer competitive annual inspection quote", "Deliver thorough, well-documented work", "Build long-term relationship through quality and trust", "Earn referrals through reputation"],
            salesTips: ["Aviation is a relationship business — trust is everything", "Thorough documentation sells your professionalism", "Be transparent about findings — never oversell unnecessary work", "Annual inspections are your gateway to ongoing maintenance revenue"],
            objectionHandling: [("The shop at the FBO is cheaper", "Price matters, but so does thoroughness. I take the time to do a complete inspection and document everything. Would you like to see a sample inspection report?"), ("I've been using the same mechanic for years", "Totally understand loyalty. If you ever need a second opinion or your mechanic is unavailable, I'm here. I also do pre-purchase inspections if you're considering another aircraft.")],
            monthlyRevenueStarter: "$3,000–$5,000/month (part-time, building clientele)",
            monthlyRevenueModerate: "$7,000–$12,000/month (full-time, 15–20 aircraft maintained)",
            monthlyRevenueStrong: "$15,000–$25,000+/month (busy shop, multiple aircraft types, IA authority)",
            estimatedMonthlyExpensesStarter: "$1,000–$2,000 (insurance, hangar rent, supplies)",
            estimatedMonthlyExpensesModerate: "$3,000–$5,000 (hangar, insurance, tools, parts inventory)",
            financialAssumptions: ["Average annual inspection: $2,500–$4,000", "Hourly rate: $85–$125", "Parts markup: 15–25%", "Target 15–25 aircraft under regular maintenance"],
            hiringPath: ["Solo A&P for first 1–2 years", "Hire apprentice mechanic as workload grows", "Add second A&P for high-volume shop", "Shop manager when operating a repair station"],
            scalingPath: ["Build base of 20+ aircraft under regular maintenance", "Obtain IA for annual inspection authority", "Apply for FAA Repair Station certificate", "Expand into turbine or multi-engine work"],
            expansionIdeas: ["FAA Part 145 Repair Station certification", "Turboprop and jet maintenance", "Avionics installation and repair", "Aircraft painting and interior refurbishment"],
            riskFactors: ["FAA A&P license requires approved training program (18–24 months)", "High liability — aviation insurance is expensive", "Seasonal demand in some regions", "Parts availability can delay aircraft return to service", "Regulatory compliance is strict and ongoing"],
            difficultyNotes: "Requires FAA-approved A&P training (18–24 months). High technical standards and regulatory compliance. Significant liability and insurance costs.",
            viabilityNotes: "Critical A&P mechanic shortage nationwide. Average salary $55K–$80K employed. Independent A&P mechanics with IA can earn $80K–$120K+. Growing general aviation fleet needs more mechanics.",
            launchSteps30Days: ["Verify A&P certificate is current and in good standing", "Obtain aviation maintenance liability insurance", "Set up LLC and business banking", "Introduce yourself at 3 local airports and FBOs", "Complete first 3–5 jobs and build documentation portfolio", "Set up invoicing system"],
            launchSteps60Days: ["Build relationships with 10+ aircraft owners", "Schedule first annual inspections", "Establish parts vendor accounts", "Join local EAA chapter and attend events", "Create aircraft type experience list for marketing"],
            launchSteps90Days: ["Evaluate client base growth and revenue", "Assess need for hangar space if working from home", "Begin IA application process if qualified", "Plan for aircraft type expansion", "Set annual revenue and client count targets"],
            fitSummary: "Aircraft mechanic (A&P) is a specialized, high-demand career with a critical workforce shortage. FAA licensing creates a strong barrier to entry. Excellent income potential for those who complete the training.",
            bestFor: ["Aviation enthusiasts who want to work with aircraft", "Detail-oriented individuals who value precision and safety", "Those willing to invest in FAA-approved training", "People seeking a specialized career with strong long-term demand"]
        )
    ]
}
