import Foundation

extension BusinessPlanDatabase {
    static let sideHustlePlans: [BusinessPlanData] = [
        BusinessPlanData(
            pathId: "trash-bin-cleaning",
            mission: "Keep residential trash bins clean, sanitized, and odor-free through a convenient monthly cleaning service.",
            vision: "Build a route-based bin cleaning business with recurring monthly subscribers and minimal overhead.",
            problemPoints: [
                "Trash bins accumulate bacteria, odors, and pests that homeowners find disgusting but rarely clean themselves.",
                "No convenient solution exists — most people tolerate dirty bins because cleaning them is unpleasant.",
                "HOAs and neighborhoods increasingly care about curb appeal and sanitation."
            ],
            solutionPoints: [
                "Monthly curbside bin cleaning and sanitizing on a set schedule.",
                "Eco-friendly cleaning solutions that eliminate odors and bacteria.",
                "Convenient service — bins are cleaned on trash day while customers are at work."
            ],
            primaryCustomer: "Homeowners in suburban neighborhoods",
            secondaryCustomer: "HOAs, property managers, and apartment complexes",
            demographics: "Homeowners aged 30-60, household income $50K+, in neighborhoods with curbside trash service",
            psychographics: "Find dirty bins gross but won't clean them, value convenience, willing to pay a small monthly fee for the service",
            buyingMotivations: ["Smelly bins attracting flies and pests", "HOA cleanliness standards", "General disgust with dirty bins", "Convenience — don't want to do it themselves"],
            serviceArea: "[Your City] suburban neighborhoods within 10 miles",
            revenueStreams: ["Monthly residential bin cleaning ($25–$50/month)", "One-time deep clean ($40–$75)", "HOA bulk contracts ($15–$25/bin/month)", "Commercial bin cleaning ($50–$100/month)"],
            upsells: ["Additional bin cleaning (recycling, green waste)", "Driveway spot cleaning on bin day", "Deodorizing treatment add-on", "Quarterly deep clean package"],
            pricingNotes: "Monthly subscription: $30–$40/month for one bin. Additional bins: $10–$15 each. HOA pricing: volume discount at $20–$25/bin. Annual prepay discount: 10% off.",
            startupCostItemsEssential: [("Pressure washer (1500+ PSI)", "$150–$400"), ("Cleaning chemicals and sanitizer", "$30–$50"), ("Hose and water source access", "$0–$50"), ("Marketing flyers", "$30–$50"), ("Liability insurance", "$300–$600/year")],
            startupCostItemsOptional: [("Dedicated bin cleaning trailer system", "$2,000–$5,000"), ("Vehicle lettering", "$200–$500"), ("Website", "$100–$300")],
            equipment: ["Pressure washer", "Cleaning solution sprayer", "Water tank (for areas without hose access)", "Brush for scrubbing"],
            tools: ["Spray bottles", "Rubber gloves and boots", "Measuring cups for solution mixing", "Before/after camera (phone)"],
            software: ["Square or Stripe for recurring billing", "Google Sheets for route tracking", "Google Business Profile"],
            vehicleNeeds: "Truck or SUV to carry pressure washer and water tank. Can start with personal vehicle.",
            workspaceNeeds: "Home-based. Store equipment in garage. All work done curbside on trash collection days.",
            legalStructureRecommendation: "Sole proprietor initially. LLC if scaling beyond 50 accounts.",
            licensesAndPermits: ["Business license", "Check local water runoff regulations"],
            insuranceNeeds: ["General liability"],
            operationsDaily: ["Check route schedule (aligned with trash pickup days)", "Load equipment and cleaning solution", "Clean bins on route (target 20–40 bins per day)", "Take before/after photos for marketing", "Process payments for new subscribers"],
            schedulingWorkflow: "Routes aligned with neighborhood trash collection schedules. Clean bins on collection day when bins are curbside and empty. Build dense routes for efficiency.",
            customerWorkflow: "Flyer/door hanger → sign up → add to route → monthly cleaning on trash day → auto-billing → quarterly check-in",
            followUpWorkflow: "Post-first-clean text with before/after photos. Monthly auto-billing. Quarterly satisfaction check. Annual renewal offer.",
            marketingChannels: ["Door hangers on trash day in target neighborhoods", "Nextdoor posts", "Facebook local groups", "Before/after photos on social media", "Yard signs on cleaning days"],
            acquisitionStrategies: ["Go door-to-door on trash day showing dirty vs clean bin comparison", "Offer free first clean to get subscribers", "Target one neighborhood at a time for route density", "Ask every subscriber to tell their neighbor"],
            referralStrategies: ["Free month for every neighbor who subscribes", "Leave door hangers on neighboring houses after cleaning", "Neighborhood group discount (5+ houses = 10% off each)"],
            partnershipIdeas: ["HOAs (bulk contract for all homes)", "Property managers", "Pressure washing companies (cross-referral)", "Waste management companies"],
            socialProofStrategies: ["Before/after photos (extremely effective for this business)", "Subscriber count in the neighborhood", "Customer testimonials about odor elimination"],
            salesProcess: ["Knock on door on trash day with a dirty bin example", "Offer free first clean", "Show before/after results immediately", "Sign up for monthly service on the spot", "Set up recurring payment"],
            salesTips: ["The gross factor sells this — show them their dirty bin", "Free first clean is your best conversion tool", "Route density is everything — focus on one neighborhood at a time", "Trash day door knocking is the most effective sales method"],
            objectionHandling: [("I can hose it out myself", "Most people say that but never actually do it! My service uses commercial sanitizer that kills bacteria and eliminates odors — a garden hose can't do that. Plus, it's done while you're at work."), ("Not worth paying for", "I understand. After the free clean, take a look at the difference. Most people are surprised how much cleaner and better-smelling their bin area becomes.")],
            monthlyRevenueStarter: "$600–$1,200/month (20–40 subscribers)",
            monthlyRevenueModerate: "$1,500–$3,000/month (50–100 subscribers)",
            monthlyRevenueStrong: "$4,000–$8,000+/month (150+ subscribers, multiple routes)",
            estimatedMonthlyExpensesStarter: "$100–$200 (chemicals, gas, flyers)",
            estimatedMonthlyExpensesModerate: "$300–$600 (add equipment maintenance, marketing)",
            financialAssumptions: ["Average subscriber: $35/month", "20–40 bins cleanable per route day", "Chemical cost per bin: $0.50–$1.00", "Route density determines profitability"],
            hiringPath: ["Solo for first 50–75 subscribers", "Hire helper for second route", "Route manager at 150+ subscribers"],
            scalingPath: ["Saturate first neighborhood, expand to adjacent areas", "Add HOA contracts for bulk accounts", "Build second route with helper", "Offer commercial bin cleaning"],
            expansionIdeas: ["Commercial dumpster cleaning", "Pressure washing services (driveways, patios)", "HOA common area cleaning", "Recycling bin and compost bin add-on"],
            riskFactors: ["Low revenue per customer requires volume", "Weather can delay routes", "Seasonal demand variation (less urgency in winter)", "Customer churn — some may cancel after a few months", "Water access can be challenging in some areas"],
            difficultyNotes: "Very easy to start. No special skills required. Main challenge is building subscriber density in neighborhoods for route efficiency.",
            viabilityNotes: "Recurring revenue model with low overhead. Best in warm climates where odor is a bigger issue. Route density determines profitability — focus on saturating neighborhoods.",
            launchSteps30Days: ["Purchase pressure washer and cleaning supplies", "Create door hangers with before/after photos", "Pick one neighborhood and go door-to-door on trash day", "Offer free first clean to every prospect", "Sign up first 15–20 subscribers", "Set up recurring billing system"],
            launchSteps60Days: ["Grow to 30–50 subscribers", "Expand to adjacent neighborhoods", "Collect before/after photos for marketing", "Post on Nextdoor and social media", "Approach HOA for bulk contract discussions"],
            launchSteps90Days: ["Evaluate route efficiency and profitability", "Target 75+ subscribers", "Assess need for helper or second route", "Refine pricing based on market response", "Plan expansion to new neighborhoods"],
            fitSummary: "Trash bin cleaning is a simple, recurring-revenue business with low startup costs. Best suited as a side hustle or part-time business. Route density in neighborhoods determines success.",
            bestFor: ["People looking for a simple side income stream", "Those who want recurring monthly revenue", "Action-oriented individuals comfortable with door-to-door sales", "Anyone willing to do work others won't — that's where the opportunity is"]
        ),

        BusinessPlanData(
            pathId: "pet-waste-removal",
            mission: "Keep yards clean and enjoyable for pet-owning families through reliable weekly pet waste removal service.",
            vision: "Build a route-based pet waste removal business with dense neighborhood coverage and loyal recurring subscribers.",
            problemPoints: [
                "Dog owners hate scooping poop but it accumulates quickly, making yards unusable.",
                "Busy pet owners don't have time for weekly yard cleanup.",
                "Landlords and HOAs need common areas kept clean from pet waste."
            ],
            solutionPoints: [
                "Reliable weekly or biweekly yard cleanup on a set schedule.",
                "Thorough service that covers the entire yard.",
                "Convenient — done while the customer is at work or away."
            ],
            primaryCustomer: "Dog owners in single-family homes",
            secondaryCustomer: "Apartment complexes, HOAs, dog parks, veterinary offices",
            demographics: "Dog owners aged 25-55, within 10-mile service radius",
            psychographics: "Love their dogs but hate the cleanup, busy schedules, willing to pay for convenience",
            buyingMotivations: ["Yard is too dirty for kids or entertaining", "Too busy to clean up regularly", "Physical limitations making scooping difficult", "Multiple dogs producing too much waste"],
            serviceArea: "[Your City] neighborhoods within 10 miles",
            revenueStreams: ["Weekly yard cleanup ($12–$20/week per dog)", "Biweekly service ($18–$25/visit)", "One-time yard cleanup ($50–$100)", "Commercial contracts for apartment complexes ($200–$500/month)", "Deodorizing add-on ($5–$10/visit)"],
            upsells: ["Additional dog pricing ($5/week per extra dog)", "Deodorizing spray treatment", "Brown spot repair seeding", "One-time spring cleanup", "Commercial property contracts"],
            pricingNotes: "Weekly service: $15/week for 1 dog, $20 for 2, $25 for 3+. Biweekly: $20–$30/visit. One-time cleanup: $50–$100 depending on yard condition.",
            startupCostItemsEssential: [("Pooper scooper and rake", "$20–$40"), ("Heavy-duty bags", "$10–$20"), ("Sanitizer spray", "$10–$15"), ("Rubber boots and gloves", "$20–$30"), ("Marketing flyers", "$20–$40")],
            startupCostItemsOptional: [("Branded shirts or hats", "$30–$60"), ("Vehicle magnets", "$50–$100"), ("Website", "$100–$200")],
            equipment: ["Commercial pooper scooper", "Rake for grass areas", "Heavy-duty waste bags", "Sanitizing spray"],
            tools: ["Rubber boots", "Disposable gloves", "Hand sanitizer", "Before/after camera (phone)"],
            software: ["Square or Stripe for recurring billing", "Google Sheets for route tracking", "Google Business Profile"],
            vehicleNeeds: "Personal vehicle for traveling between yards. No special modifications needed.",
            workspaceNeeds: "Home-based. Minimal equipment storage. All work done at customer yards.",
            legalStructureRecommendation: "Sole proprietor is sufficient for this business size.",
            licensesAndPermits: ["Business license"],
            insuranceNeeds: ["General liability (recommended but not always required for this service)"],
            operationsDaily: ["Review route schedule", "Drive to first yard on route", "Complete cleanup (10–15 minutes per yard)", "Move to next yard", "Process new subscriber sign-ups", "Distribute flyers to neighboring houses"],
            schedulingWorkflow: "Fixed weekly routes by neighborhood. Same day each week per client. 15–25 yards per route day. Geographic clustering for efficiency.",
            customerWorkflow: "Flyer or Nextdoor post → sign up → add to weekly route → service begins → auto-billing → quarterly check-in",
            followUpWorkflow: "Confirmation after first service. Monthly auto-billing. Seasonal one-time cleanup offers. Text if schedule changes due to weather.",
            marketingChannels: ["Door-to-door flyers in neighborhoods with visible dog ownership", "Nextdoor", "Facebook local pet owner groups", "Veterinary office bulletin boards", "Pet store bulletin boards"],
            acquisitionStrategies: ["Flyer neighborhoods where you see dogs in yards", "Post in pet owner Facebook groups", "Partner with veterinary offices for referrals", "Offer free first cleanup to new subscribers"],
            referralStrategies: ["Free week for every referred neighbor who subscribes", "Leave flyers on neighboring doors", "Dog park networking"],
            partnershipIdeas: ["Veterinary offices (flyers and referrals)", "Pet stores", "Dog walkers and pet sitters (cross-referral)", "Apartment complexes with pet-friendly policies"],
            socialProofStrategies: ["Before/after yard photos", "Happy customer testimonials", "Subscriber count in the neighborhood", "Consistent service reliability"],
            salesProcess: ["Distribute flyers in target neighborhoods", "Offer free first cleanup", "Show the clean yard result", "Sign up for weekly service", "Set up recurring payment", "Ask for neighbor referral"],
            salesTips: ["Nobody wants to talk about poop — but everyone with a dog has the problem", "Free first cleanup converts well because the result is immediately visible", "Route density matters — focus on one neighborhood at a time", "Spring is your best acquisition season"],
            objectionHandling: [("It's not worth paying for", "I totally get it. But imagine never having to scoop again — and your yard is always clean for the kids. It's less than a cup of coffee per day."), ("I can do it myself", "Most people can! But life gets busy and it piles up. I keep it consistently clean so you never have to think about it.")],
            monthlyRevenueStarter: "$500–$1,000/month (15–30 weekly subscribers)",
            monthlyRevenueModerate: "$1,500–$2,500/month (40–70 subscribers)",
            monthlyRevenueStrong: "$3,000–$5,000+/month (100+ subscribers, commercial contracts)",
            estimatedMonthlyExpensesStarter: "$50–$100 (bags, gas, supplies)",
            estimatedMonthlyExpensesModerate: "$150–$300 (add marketing, vehicle costs)",
            financialAssumptions: ["Average subscriber: $60–$80/month", "15–25 yards per route day", "Time per yard: 10–15 minutes", "Low supply costs — mostly labor and gas"],
            hiringPath: ["Solo for first 50 subscribers", "Hire part-time helper for second route", "Route manager at 100+ subscribers"],
            scalingPath: ["Saturate first neighborhood", "Expand to adjacent neighborhoods", "Add commercial contracts", "Build second route with helper"],
            expansionIdeas: ["Yard deodorizing service", "Dog walking or pet sitting add-on", "Commercial property pet area maintenance", "Seasonal yard cleanup services"],
            riskFactors: ["Low revenue per customer requires volume", "Weather delays (rain, snow)", "Physically repetitive work", "Some customers cancel after a few months", "Competing with free (customers can do it themselves)"],
            difficultyNotes: "Easiest business to start. No skills, training, or equipment needed. Main challenge is acquiring enough subscribers for route efficiency.",
            viabilityNotes: "Simple recurring revenue with very low overhead. Works best as a side hustle or combined with other pet or yard services. Scales through route density.",
            launchSteps30Days: ["Buy scooping equipment and bags", "Create simple flyers", "Target one neighborhood and flyer 50 houses", "Offer free first cleanup", "Sign up first 10–15 subscribers", "Set up recurring billing"],
            launchSteps60Days: ["Grow to 25–40 subscribers", "Expand to second neighborhood", "Post on Nextdoor and pet owner groups", "Visit 3 veterinary offices with flyers", "Ask subscribers for neighbor referrals"],
            launchSteps90Days: ["Target 50+ subscribers", "Evaluate route efficiency", "Assess profitability and pricing", "Consider adding deodorizing service", "Plan expansion strategy"],
            fitSummary: "Pet waste removal is the simplest recurring-revenue business to start. Minimal investment, no skills required. Best as a side hustle with potential to grow through route density and commercial contracts.",
            bestFor: ["People wanting the simplest possible side income", "Those comfortable with outdoor physical work", "Action-oriented individuals who can sell door-to-door", "Anyone looking for reliable recurring revenue with minimal startup cost"]
        ),

        BusinessPlanData(
            pathId: "balloon-decorating",
            mission: "Create memorable balloon decorations for parties, events, and celebrations that wow guests and make occasions feel special.",
            vision: "Build a balloon decorating business known for creative designs and reliable event execution.",
            problemPoints: [
                "Party hosts want impressive decorations but lack the skills and time to create them.",
                "Balloon arches, garlands, and centerpieces are trending but difficult to DIY well.",
                "Event venues and businesses need professional decor for openings, promotions, and celebrations."
            ],
            solutionPoints: [
                "Custom balloon installations designed for each event's theme and color scheme.",
                "Professional setup and teardown — the client doesn't have to do anything.",
                "Instagram-worthy designs that guests will photograph and share."
            ],
            primaryCustomer: "Parents planning children's birthday parties",
            secondaryCustomer: "Event planners, businesses (grand openings), and individuals celebrating milestones",
            demographics: "Parents aged 25-45, within 15-mile radius, planning celebrations",
            psychographics: "Want picture-perfect events, influenced by Instagram and Pinterest, willing to spend on decorations that look professional",
            buyingMotivations: ["Child's birthday party", "Baby shower or gender reveal", "Business grand opening", "Wedding or graduation celebration"],
            serviceArea: "[Your City] and surrounding areas within 15 miles",
            revenueStreams: ["Balloon garlands ($100–$300)", "Balloon arches ($150–$500)", "Centerpieces ($15–$40 each)", "Full event packages ($300–$1,000+)", "Corporate event decor ($500–$2,000+)"],
            upsells: ["Number and letter balloons", "Confetti-filled balloons", "Delivery and setup service", "Photo backdrop installations", "Themed custom designs"],
            pricingNotes: "Price by installation type and size. Basic garland: $100–$150. Full arch: $200–$400. Event packages vary by scope. Always charge for delivery and setup.",
            startupCostItemsEssential: [("Balloon pump (electric)", "$30–$60"), ("Balloon variety pack (multiple colors/sizes)", "$50–$100"), ("Balloon tape, glue dots, and string", "$20–$30"), ("Transport bins and bags", "$20–$40")],
            startupCostItemsOptional: [("Balloon sizing tool", "$15–$25"), ("Backdrop stand", "$30–$60"), ("Business cards", "$20–$30"), ("Website", "$100–$200")],
            equipment: ["Electric balloon pump", "Manual hand pump (backup)", "Balloon tape strips", "Fishing line and hooks", "Transport bags"],
            tools: ["Scissors", "Glue dots and adhesive", "Measuring tape", "Balloon sizer template", "Step stool or ladder"],
            software: ["Instagram for portfolio", "Square for invoicing", "Google Business Profile"],
            vehicleNeeds: "Vehicle large enough to transport inflated balloon installations. SUV or van preferred.",
            workspaceNeeds: "Home-based prep area. Inflate and assemble at home, transport to venue for final setup.",
            legalStructureRecommendation: "Sole proprietor is fine for this business size.",
            licensesAndPermits: ["Business license"],
            insuranceNeeds: ["General liability (recommended for event work)"],
            operationsDaily: ["Confirm upcoming event details", "Purchase balloons in event colors", "Inflate and assemble installations", "Transport and set up at venue", "Take portfolio photos", "Post on social media", "Follow up with past clients"],
            schedulingWorkflow: "Events booked 1–4 weeks in advance. Prep work done day before or morning of. Setup at venue 1–2 hours before event.",
            customerWorkflow: "Inquiry → discuss event theme, colors, budget → quote → deposit (50%) → prep → setup → final payment → portfolio photos → review request",
            followUpWorkflow: "Post-event thank you text. Request review and photos. Add to email list for future promotions. Holiday/birthday reminder outreach.",
            marketingChannels: ["Instagram (essential — visual business)", "Pinterest boards for inspiration", "Facebook local event and party groups", "Nextdoor", "Event venue partnerships"],
            acquisitionStrategies: ["Build Instagram portfolio with your best designs", "Offer discounted first installation to build portfolio", "Post in party planning Facebook groups", "Partner with event venues and party supply stores"],
            referralStrategies: ["$25 off next booking for referrals", "Include business cards with every installation", "Tag clients in Instagram posts (they share with friends)"],
            partnershipIdeas: ["Event venues (preferred decorator)", "Party supply stores (referral)", "Event planners", "Photographers (styled shoot collaboration)"],
            socialProofStrategies: ["Instagram portfolio of installations", "Client testimonials and event photos", "Video of setup process (satisfying content)", "Tag and share client event photos"],
            salesProcess: ["Respond to inquiry with availability", "Ask about theme, colors, venue, and budget", "Send quote with inspiration photos", "Collect 50% deposit to confirm", "Complete setup on event day", "Request review and referral"],
            salesTips: ["Instagram is your #1 sales tool — invest in great photos of your work", "Offer packages at different price points to fit various budgets", "Events are emotional purchases — tap into the excitement of the celebration", "Word of mouth at events generates future bookings"],
            objectionHandling: [("I can buy balloons myself", "You absolutely can! The difference is the design skill and time. A professional installation takes hours and specific techniques. You get to enjoy the party instead of stressing over decorations."), ("Too expensive", "I have a mini package that starts at $100 for a simple garland. It makes a big impact without breaking the budget.")],
            monthlyRevenueStarter: "$400–$800/month (2–4 events/month, weekends)",
            monthlyRevenueModerate: "$1,000–$2,000/month (4–8 events/month)",
            monthlyRevenueStrong: "$2,500–$5,000+/month (8+ events, corporate clients)",
            estimatedMonthlyExpensesStarter: "$50–$100 (balloons, supplies, gas)",
            estimatedMonthlyExpensesModerate: "$150–$300 (add marketing, premium supplies)",
            financialAssumptions: ["Average event: $200–$350", "Material cost: 15–25% of price", "Events primarily on weekends", "Corporate events have higher budgets"],
            hiringPath: ["Solo for all events initially", "Hire helper for large installations", "Train assistant to handle smaller events independently"],
            scalingPath: ["Build Instagram following and portfolio", "Add corporate event services", "Offer balloon decorating workshops", "Expand to full event styling"],
            expansionIdeas: ["Full event decorating (not just balloons)", "Corporate event services", "Balloon decorating workshops and classes", "Themed party packages"],
            riskFactors: ["Seasonal demand (birthday season, holidays)", "Balloons are fragile — popping and weather issues", "Weekend-heavy schedule", "Limited per-event revenue", "Trend-dependent — balloon styles change"],
            difficultyNotes: "Low skill barrier. Learn techniques through tutorials and practice. Practice on friends' parties. Skills improve quickly with each event.",
            viabilityNotes: "Weekend side hustle with decent per-event revenue. Best when combined with other event services. Instagram-driven business — visual portfolio is essential.",
            launchSteps30Days: ["Purchase balloon supplies and electric pump", "Study tutorials and practice 3–5 designs", "Create Instagram page with practice photos", "Do 2–3 events for friends/family at cost to build portfolio", "Post portfolio photos on Instagram and Facebook", "Sign up first 2 paid events"],
            launchSteps60Days: ["Complete 5+ events and build portfolio", "Join party planning Facebook groups", "Connect with local event venues", "Reach 100+ Instagram followers", "Refine pricing based on demand"],
            launchSteps90Days: ["Evaluate bookings and revenue", "Approach corporate clients for holiday events", "Develop signature design styles", "Launch referral program", "Set monthly booking targets"],
            fitSummary: "Balloon decorating is a creative weekend side hustle with decent per-event income. Instagram-driven marketing makes it easy to showcase your work. Best for creative people who enjoy events.",
            bestFor: ["Creative individuals who enjoy hands-on decorating", "People seeking a fun weekend side hustle", "Those with strong social media skills", "Anyone who enjoys making celebrations special"]
        ),

        BusinessPlanData(
            pathId: "face-painting",
            mission: "Bring joy to children's events and parties through creative, safe face painting that delights kids and impresses parents.",
            vision: "Become the go-to face painter for birthday parties, school events, and community festivals in the local area.",
            problemPoints: [
                "Parents want entertaining activities at children's parties beyond just cake and presents.",
                "Finding a reliable, talented face painter is difficult through generic search.",
                "Community events and festivals need engaging activities for children."
            ],
            solutionPoints: [
                "Professional face painting using FDA-approved, hypoallergenic paints safe for children.",
                "Wide design catalog from simple cheek art to full-face transformations.",
                "Reliable, friendly service that keeps kids entertained and parents relaxed."
            ],
            primaryCustomer: "Parents planning children's birthday parties (ages 3-10)",
            secondaryCustomer: "Schools, daycares, community events, corporate family events, and festivals",
            demographics: "Parents aged 28-45 planning children's events, within 15-mile radius",
            psychographics: "Want memorable party experiences, care about child safety, value creative entertainment",
            buyingMotivations: ["Birthday party entertainment", "School or daycare events", "Community festivals", "Holiday celebrations", "Corporate family days"],
            serviceArea: "[Your City] and surrounding areas within 15 miles",
            revenueStreams: ["Birthday parties ($100–$200 for 2 hours)", "School and daycare events ($150–$300)", "Festival and community events ($50–$75/hour)", "Corporate events ($200–$400)", "Add-on glitter tattoos ($50–$100 extra)"],
            upsells: ["Glitter tattoos", "Temporary tattoos", "Extended time bookings", "Adult face painting for themed events", "Body art for festivals"],
            pricingNotes: "Hourly rate: $50–$75/hour. Birthday party package: $125–$200 for 2 hours. Festival rate: $50–$75/hour (volume). Always include setup/cleanup time in quote.",
            startupCostItemsEssential: [("Professional face paint kit (FDA-approved)", "$50–$100"), ("Brushes and sponges set", "$20–$40"), ("Mirror and chair", "$20–$30"), ("Portfolio binder or tablet", "$0–$50"), ("Hand sanitizer and cleaning supplies", "$10–$15")],
            startupCostItemsOptional: [("Glitter and gem supplies", "$20–$40"), ("Banner and signage", "$30–$50"), ("Business cards", "$20–$30"), ("Website", "$100–$200")],
            equipment: ["Professional face paint palette", "Brush set (various sizes)", "Sponge set", "Water containers", "Portable mirror"],
            tools: ["Stencils for quick designs", "Glitter and body gems", "Baby wipes for cleanup", "Spray bottle", "Design reference cards"],
            software: ["Instagram for portfolio", "Square for payments", "Google Calendar for scheduling"],
            vehicleNeeds: "Personal vehicle to transport supplies to events. All supplies fit in a small bag.",
            workspaceNeeds: "Home-based. Practice at home. All work at event venues.",
            legalStructureRecommendation: "Sole proprietor is fine for this business.",
            licensesAndPermits: ["Business license", "Some cities require a performer's permit for public events"],
            insuranceNeeds: ["General liability (recommended when working with children at events)"],
            operationsDaily: ["Confirm event details and arrival time", "Pack supplies and reference designs", "Travel to event and set up station", "Paint faces (5–10 minutes per child)", "Clean up and pack", "Post photos on social media", "Follow up with client"],
            schedulingWorkflow: "Primarily weekend bookings. Book 1–3 events per weekend day. Events booked 1–4 weeks in advance. Festival season: book months ahead.",
            customerWorkflow: "Inquiry → discuss event details → quote → deposit → arrive and set up → paint → pack up → final payment → review request",
            followUpWorkflow: "Thank you text after event. Request review and portfolio photos. Add to mailing list. Birthday reminder for next year.",
            marketingChannels: ["Instagram portfolio", "Facebook parenting and event groups", "Nextdoor", "School and community bulletin boards", "Event planning websites"],
            acquisitionStrategies: ["Build Instagram portfolio with your best face painting designs", "Offer to paint at friends' parties for portfolio building", "Post in parenting and birthday party Facebook groups", "Leave flyers at party supply stores"],
            referralStrategies: ["$20 off next booking for referrals", "Business cards given to every parent at events", "Encourage parents to share photos and tag you"],
            partnershipIdeas: ["Event planners", "Balloon decorators (bundle services)", "Party venues", "Children's entertainers (magicians, clowns)"],
            socialProofStrategies: ["Instagram portfolio of painted faces", "Parent testimonials", "Video of painting process", "Happy kid reaction photos (with parent permission)"],
            salesProcess: ["Respond to inquiry with availability and pricing", "Share portfolio photos", "Confirm event details and design preferences", "Collect deposit to secure booking", "Deliver great experience at event", "Request review and referral"],
            salesTips: ["Your portfolio photos sell the service — invest in good photos of your work", "Kids' reactions at events generate bookings from other parents watching", "Partner with other party entertainers for package deals", "Festival and fair work builds exposure fast"],
            objectionHandling: [("Too expensive", "I have a shorter package at a lower price point — 1 hour covers 8–12 kids and still makes a big impact."), ("My kid might be allergic", "I only use FDA-approved, hypoallergenic face paints designed for children's skin. I can also do a small test patch first.")],
            monthlyRevenueStarter: "$300–$600/month (2–3 events/month)",
            monthlyRevenueModerate: "$800–$1,500/month (4–8 events/month)",
            monthlyRevenueStrong: "$2,000–$3,000+/month (8+ events, festival season)",
            estimatedMonthlyExpensesStarter: "$20–$50 (paint, supplies, gas)",
            estimatedMonthlyExpensesModerate: "$50–$100 (add marketing, premium supplies)",
            financialAssumptions: ["Average event: $150–$200", "Supply cost per event: $5–$15", "Primarily weekend income", "Festival season (summer) is peak"],
            hiringPath: ["Solo for all events", "Train a second painter for double bookings", "Team of painters for festival season"],
            scalingPath: ["Build portfolio and reputation locally", "Add festival and corporate event bookings", "Offer face painting + balloon decorating packages", "Train additional painters"],
            expansionIdeas: ["Balloon decorating combo service", "Glitter tattoo specialization", "Festival circuit work", "Face painting classes and tutorials"],
            riskFactors: ["Weekend-only income", "Seasonal demand fluctuation", "Physical demands (sitting and painting for hours)", "Weather affects outdoor events", "Limited per-event earning potential"],
            difficultyNotes: "Moderate skill required. Practice daily for 2–4 weeks to build confidence. Study tutorials and reference guides for technique. Start with simple designs and build complexity.",
            viabilityNotes: "Fun weekend side hustle with consistent party demand. Best combined with other event services. Festival season provides peak earning opportunities.",
            launchSteps30Days: ["Purchase FDA-approved face paint kit and brushes", "Practice 10+ designs from tutorials and reference guides", "Paint friends' and family's kids for portfolio photos", "Create Instagram page with portfolio", "Post in 5 local parenting groups", "Book first 2–3 paid events"],
            launchSteps60Days: ["Complete 5+ events and expand portfolio", "Build relationships with party venues", "Join event entertainment Facebook groups", "Apply to local festivals and fairs", "Collect parent testimonials"],
            launchSteps90Days: ["Evaluate bookings and revenue", "Refine pricing and packages", "Develop signature designs", "Plan for festival season bookings", "Set monthly event targets"],
            fitSummary: "Face painting is a creative weekend side hustle that brings joy to children's events. Low startup cost with fun, rewarding work. Best as supplemental income alongside other work.",
            bestFor: ["Creative individuals who enjoy working with children", "People seeking a fun weekend side income", "Those with artistic skills or willingness to learn", "Anyone who enjoys events and celebrations"]
        ),

        BusinessPlanData(
            pathId: "event-cleanup",
            mission: "Provide fast, thorough post-event cleanup so hosts can enjoy their events without dreading the aftermath.",
            vision: "Build a reliable event cleanup service that becomes the go-to for venues, party hosts, and event planners.",
            problemPoints: [
                "After a party or event, hosts are exhausted and face hours of cleanup work.",
                "Event venues need fast turnaround between events — cleanup must be quick and thorough.",
                "Large events (weddings, corporate) generate massive amounts of waste that overwhelm hosts."
            ],
            solutionPoints: [
                "Professional post-event cleanup crew that handles everything — trash, dishes, furniture, decor removal.",
                "Fast turnaround for venues needing quick reset between events.",
                "Available for late-night and next-morning cleanup."
            ],
            primaryCustomer: "Party hosts and families after celebrations",
            secondaryCustomer: "Event venues, wedding planners, corporate event coordinators",
            demographics: "Event hosts aged 25-55, within 15-mile radius",
            psychographics: "Exhausted after hosting, willing to pay to avoid cleanup stress, want the house back to normal quickly",
            buyingMotivations: ["Post-party exhaustion — don't want to clean up", "Venue turnaround requirements", "Large event with too much waste for one person", "Next-morning cleanup after late events"],
            serviceArea: "[Your City] and surrounding areas within 15 miles",
            revenueStreams: ["Residential party cleanup ($150–$400)", "Venue turnaround cleanup ($200–$600)", "Wedding cleanup ($300–$800)", "Corporate event cleanup ($300–$1,000+)", "Next-morning service ($100–$250)"],
            upsells: ["Same-night cleanup (premium pricing)", "Furniture rental return coordination", "Decoration takedown and removal", "Trash hauling to dump", "Deep cleaning after event"],
            pricingNotes: "Base rate: $50–$75/hour per person. Flat rate packages for standard events. Late-night/same-night premium of 25–50%. Minimum 2-hour booking.",
            startupCostItemsEssential: [("Heavy-duty trash bags", "$15–$25"), ("Cleaning supplies", "$30–$50"), ("Rubber gloves and basics", "$10–$20"), ("Broom, mop, and bucket", "$30–$50")],
            startupCostItemsOptional: [("Carpet cleaner rental capability", "$0–$50/use"), ("Vehicle for trash hauling", "$0–$5,000"), ("Business cards and flyers", "$30–$50")],
            equipment: ["Heavy-duty trash bags", "Broom and dustpan", "Mop and bucket", "All-purpose cleaning spray", "Rubber gloves"],
            tools: ["Folding table dolly (for furniture)", "Extension grabber tool", "Flashlight for outdoor events", "Spray bottles"],
            software: ["Google Calendar", "Square or Venmo for payments", "Google Business Profile"],
            vehicleNeeds: "Vehicle for trash hauling and transporting cleaning supplies. Truck bed or SUV useful for larger events.",
            workspaceNeeds: "Home-based. Store supplies at home. All work at event locations.",
            legalStructureRecommendation: "Sole proprietor is fine for this business.",
            licensesAndPermits: ["Business license"],
            insuranceNeeds: ["General liability (recommended for working in private homes and venues)"],
            operationsDaily: ["Confirm event details and arrival time", "Load vehicle with cleaning supplies", "Arrive at venue at scheduled time", "Complete cleanup systematically", "Haul trash and waste", "Final walkthrough with client", "Invoice and collect payment"],
            schedulingWorkflow: "Primarily weekend evenings and next mornings. Book 1–3 events per weekend. Weeknight corporate events occasionally.",
            customerWorkflow: "Inquiry → discuss event details and scope → quote → confirm booking → arrive post-event → complete cleanup → walkthrough → payment → review request",
            followUpWorkflow: "Thank you text after service. Request review. Add to mailing list. Reach out before holidays and event seasons.",
            marketingChannels: ["Event planning Facebook groups", "Nextdoor", "Event venue partnerships", "Wedding planner referrals", "Google Business Profile"],
            acquisitionStrategies: ["Partner with event venues for preferred cleanup vendor status", "Connect with wedding planners and event coordinators", "Post in party planning and event groups", "Offer first cleanup at a discount to build reviews"],
            referralStrategies: ["$25 off next booking for referrals", "Business cards at every event", "Venue referral partnership"],
            partnershipIdeas: ["Event venues (preferred vendor)", "Wedding planners", "Catering companies", "Party rental companies"],
            socialProofStrategies: ["Before/after photos of event cleanup", "Client testimonials", "Venue partner endorsements", "Speed and thoroughness metrics"],
            salesProcess: ["Respond to inquiry quickly", "Ask about event type, guest count, and venue", "Provide quote based on scope", "Confirm booking with deposit", "Complete cleanup thoroughly", "Request review"],
            salesTips: ["Partner with venues — they're your best source of repeat business", "Market to exhausted post-event hosts — the timing of your pitch matters", "Offer same-night cleanup at premium prices — people will pay", "Wedding cleanup is the highest-paying segment"],
            objectionHandling: [("We'll clean up ourselves", "Totally understand! But after hosting 50 guests for 5 hours, the last thing you'll want to do is clean for 3 more hours. I'll have it done in 90 minutes while you relax."), ("Too expensive", "I have a basic package that covers trash removal and surface cleanup. You handle the dishes, I handle the rest.")],
            monthlyRevenueStarter: "$400–$800/month (2–4 events/month)",
            monthlyRevenueModerate: "$1,000–$2,000/month (4–8 events/month)",
            monthlyRevenueStrong: "$2,500–$4,000+/month (8+ events, venue contracts)",
            estimatedMonthlyExpensesStarter: "$30–$60 (supplies, bags, gas)",
            estimatedMonthlyExpensesModerate: "$80–$150 (add dump fees, marketing)",
            financialAssumptions: ["Average event cleanup: $200–$350", "Supply cost per event: $10–$20", "Primarily weekend and evening work", "Venue partnerships provide consistent bookings"],
            hiringPath: ["Solo for smaller events", "Hire helper for larger events", "Build small crew for multiple bookings per night"],
            scalingPath: ["Build venue partnerships for consistent bookings", "Add specialty services (deep clean, furniture return)", "Build crew for multiple simultaneous events", "Expand to corporate event management"],
            expansionIdeas: ["General cleaning service (residential/commercial)", "Event setup AND cleanup packages", "Venue management partnerships", "Trash hauling and junk removal"],
            riskFactors: ["Weekend and evening schedule", "Physically demanding work", "Irregular booking schedule", "Late-night work", "Limited earning potential per event"],
            difficultyNotes: "No special skills required. Physical work. Main challenge is building venue partnerships and consistent bookings.",
            viabilityNotes: "Good weekend side hustle, especially combined with other event services. Venue partnerships provide the most consistent work. Best in areas with active event scenes.",
            launchSteps30Days: ["Purchase basic cleaning supplies", "Create flyers and business cards", "Contact 5 local event venues about cleanup services", "Post in event planning Facebook groups", "Complete first 2–3 events (offer discount for reviews)", "Collect before/after photos"],
            launchSteps60Days: ["Build venue partnerships", "Connect with wedding planners and caterers", "Grow to 4–6 events per month", "Collect testimonials", "Refine pricing based on job scope"],
            launchSteps90Days: ["Evaluate revenue and booking consistency", "Assess need for helper on larger events", "Expand marketing to corporate events", "Set monthly booking and revenue targets", "Plan for holiday event season"],
            fitSummary: "Event cleanup is a straightforward side hustle with decent per-event pay. Best when combined with venue partnerships for consistent bookings. Weekend and evening work schedule.",
            bestFor: ["People comfortable with physical cleanup work", "Those available on weekends and evenings", "Anyone who enjoys being part of the events scene", "People looking for a simple side hustle with no special skills needed"]
        )
    ]
}
