import Foundation

extension BusinessPlanDatabase {
    static let serviceBusinessPlans: [BusinessPlanData] = [
        BusinessPlanData(
            pathId: "pressure-washing",
            mission: "Restore and protect residential and commercial properties through professional pressure washing with reliable service and visible results.",
            vision: "Build a pressure washing business that grows from residential driveways into commercial contracts and fleet accounts.",
            problemPoints: [
                "Homeowners let driveways, decks, and siding deteriorate because they lack the equipment and time.",
                "Dirty exteriors reduce curb appeal and property value.",
                "Commercial properties need regular cleaning to maintain professional appearance."
            ],
            solutionPoints: [
                "Professional-grade pressure washing that delivers dramatic, visible results.",
                "Before/after photos that speak for themselves — the best marketing tool in the business.",
                "Convenient scheduling with recurring service plans for commercial clients."
            ],
            primaryCustomer: "Homeowners wanting to restore driveways, decks, siding, and patios",
            secondaryCustomer: "Property managers, HOAs, real estate agents preparing listings, and commercial properties",
            demographics: "Homeowners aged 30-65, household income $50K+, within 15-mile service radius",
            psychographics: "Take pride in their property appearance, motivated by visible before/after results, prefer hiring out physical labor",
            buyingMotivations: ["Dirty driveway or walkways", "Preparing home for sale", "HOA compliance", "Annual spring cleaning", "Commercial property maintenance"],
            serviceArea: "[Your City] and surrounding neighborhoods within 15 miles",
            revenueStreams: ["Residential driveway/walkway ($100–$250)", "Full house exterior ($250–$500)", "Deck and fence cleaning ($150–$400)", "Commercial contracts ($300–$1,000+/visit)", "Recurring maintenance plans ($100–$300/month)"],
            upsells: ["Deck staining after cleaning", "Gutter cleaning add-on", "Soft wash for delicate surfaces", "Driveway sealing after pressure washing", "Window cleaning bundle"],
            pricingNotes: "Price by square footage for consistency. Residential driveways average $0.15–$0.30/sq ft. Bundle driveway + walkway + patio for higher tickets. Commercial quoted per visit.",
            startupCostItemsEssential: [("Pressure washer (3000+ PSI)", "$300–$800"), ("Surface cleaner attachment", "$100–$300"), ("Hoses, nozzles, and fittings", "$100–$200"), ("Cleaning chemicals and surfactants", "$50–$100"), ("Transportation (truck or trailer)", "$0–$5,000")],
            startupCostItemsOptional: [("Soft wash system", "$500–$1,500"), ("Water tank for remote jobs", "$200–$500"), ("Vehicle lettering/wrap", "$500–$2,000"), ("Website", "$200–$500")],
            equipment: ["Commercial pressure washer (3000–4000 PSI)", "Surface cleaner for flat surfaces", "Soft wash pump and system", "Extension wands", "Water tank (for areas without hose access)"],
            tools: ["Various nozzle tips (0°, 15°, 25°, 40°)", "Chemical injector", "Safety goggles and boots", "Measuring wheel for quoting", "Before/after camera (phone works)"],
            software: ["Square or Stripe for invoicing", "Google Business Profile", "Instagram for before/after portfolio"],
            vehicleNeeds: "Pickup truck or SUV with trailer to haul equipment. Pressure washer, hoses, and chemicals need secure storage.",
            workspaceNeeds: "Home-based. Store equipment in garage or shed. All work is performed on-site.",
            legalStructureRecommendation: "LLC recommended once revenue exceeds $2,000/month. Protects personal assets if property damage occurs during cleaning.",
            licensesAndPermits: ["Business license", "Check local water runoff regulations", "Some areas require wastewater capture compliance"],
            insuranceNeeds: ["General liability ($500K–$1M)", "Commercial auto if using a dedicated work vehicle"],
            operationsDaily: ["Confirm appointments and check weather", "Load equipment and chemicals", "Travel to job site", "Take before photos", "Complete pressure washing", "Take after photos and send to customer", "Invoice and collect payment", "Post before/after on social media"],
            schedulingWorkflow: "Book 3–5 residential jobs per day. Schedule in geographic clusters. Keep weather backup days. Commercial jobs on recurring weekly/monthly schedule.",
            customerWorkflow: "Inquiry → provide quote (in-person or from photos) → schedule → complete work → send before/after → invoice → request review → follow up for recurring service",
            followUpWorkflow: "Send before/after photos same day. Request Google review within 24 hours. Reminder at 6 months for repeat service. Spring/fall seasonal outreach.",
            marketingChannels: ["Before/after posts on Facebook and Instagram", "Nextdoor recommendations", "Google Business Profile", "Door hangers in neighborhoods where you work", "Yard signs at active job sites"],
            acquisitionStrategies: ["Do one free driveway to get your first before/after photos", "Post before/after content weekly on social media", "Knock on doors in the neighborhood while working a job", "Offer 10% off for neighbors of current clients"],
            referralStrategies: ["$25 off next service for every referral that books", "Leave door hangers on neighboring houses after completing a job", "Ask every satisfied customer for a Google review"],
            partnershipIdeas: ["Real estate agents (pre-listing curb appeal)", "Property management companies (recurring contracts)", "Deck builders and landscapers (cross-referral)", "Window cleaning companies (bundle services)"],
            socialProofStrategies: ["Before/after photo portfolio (most powerful tool)", "Google review count", "Video timelapses of cleaning process", "Customer testimonials"],
            salesProcess: ["Respond to inquiry within 1 hour", "Quote from photos or in-person", "Offer bundle discount (driveway + walkway + patio)", "Schedule within 3–5 days", "Complete work and send before/after", "Request review and referral"],
            salesTips: ["Before/after photos sell this business — always take them", "Offer a small neighbor discount while you're already in the area", "Bundle services for a higher ticket", "Spring and fall are peak seasons — book ahead"],
            objectionHandling: [("I can rent one and do it myself", "Absolutely! Keep in mind that incorrect pressure or technique can damage concrete and siding. My equipment is commercial grade and I know the right pressure for each surface. Plus, you save a full day of work."), ("Too expensive", "I can adjust the scope. Would you like to start with just the driveway? Once you see the results, you can decide about the rest.")],
            monthlyRevenueStarter: "$2,000–$4,000/month (weekends only, 4–6 jobs/week)",
            monthlyRevenueModerate: "$5,000–$8,000/month (full-time, 15–20 jobs/week)",
            monthlyRevenueStrong: "$10,000–$15,000+/month (with helper, commercial contracts)",
            estimatedMonthlyExpensesStarter: "$300–$600 (gas, chemicals, insurance, equipment maintenance)",
            estimatedMonthlyExpensesModerate: "$800–$1,500 (add vehicle costs, marketing, helper pay)",
            financialAssumptions: ["Average residential job: $200–$350", "Average commercial job: $500–$1,000", "Chemical costs: 5–10% of revenue", "Equipment replacement: budget $500–$1,000/year"],
            hiringPath: ["Solo for first 3–6 months", "Hire part-time helper for larger jobs", "Add second crew when booking 3+ weeks out", "Office/scheduling assistant at 30+ jobs/week"],
            scalingPath: ["Start residential, add commercial contracts", "Build second crew with dedicated equipment", "Add soft washing for roofs and delicate surfaces", "Offer fleet and parking lot cleaning"],
            expansionIdeas: ["Soft wash roof cleaning", "Commercial parking lot and building washing", "Fleet vehicle washing contracts", "Concrete sealing after pressure washing"],
            riskFactors: ["Weather dependent — rain cancels jobs", "Property damage risk (incorrect pressure on surfaces)", "Seasonal demand variation", "Equipment requires regular maintenance", "Physical labor in heat and sun"],
            difficultyNotes: "Low barrier to entry. Can start with basic equipment and upgrade. Watch YouTube tutorials for technique. Practice on your own property first.",
            viabilityNotes: "Pressure washing is one of the easiest service businesses to start. High demand, visible results, and strong word-of-mouth growth. Before/after photos are your best marketing tool.",
            launchSteps30Days: ["Purchase pressure washer and essential supplies", "Practice on your own property and friends' properties", "Take before/after photos for portfolio", "Create Google Business Profile and social media accounts", "Post in 5 local Facebook groups and Nextdoor", "Complete first 5 paid jobs and collect reviews"],
            launchSteps60Days: ["Build portfolio to 10+ before/after photo sets", "Print door hangers for neighborhoods", "Connect with 3 real estate agents", "Offer bundle packages for higher tickets", "Evaluate need for additional equipment"],
            launchSteps90Days: ["Reach 10+ Google reviews", "Approach property management companies for contracts", "Consider adding soft wash capabilities", "Evaluate hiring a helper", "Set monthly revenue targets for growth"],
            fitSummary: "Pressure washing is a proven, low-investment service business with high demand and fast revenue potential. Before/after results create natural word-of-mouth marketing. Scales well with additional crews and commercial contracts.",
            bestFor: ["Action-oriented people who want to start earning quickly", "Those who enjoy physical outdoor work with visible results", "Entrepreneurs looking for a low-cost, scalable service business", "Anyone who enjoys the satisfaction of dramatic before/after transformations"]
        ),

        BusinessPlanData(
            pathId: "cleaning-services-commercial",
            mission: "Deliver consistent, reliable commercial cleaning that helps businesses maintain professional environments for their employees and customers.",
            vision: "Build a commercial cleaning company with long-term contracts, multiple crews, and reputation for dependability.",
            problemPoints: [
                "Office managers struggle to find cleaning services that show up consistently and do thorough work.",
                "High turnover in the cleaning industry means inconsistent quality from many providers.",
                "Small businesses can't afford premium janitorial services but still need clean spaces."
            ],
            solutionPoints: [
                "Consistent, reliable cleaning on a set schedule — same cleaner every visit.",
                "Quality checklists and photo documentation of completed work.",
                "Affordable pricing designed for small to mid-size businesses."
            ],
            primaryCustomer: "Small offices, retail stores, and professional services (dental, law, accounting)",
            secondaryCustomer: "Medical offices, restaurants, property managers of commercial spaces",
            demographics: "Business owners and office managers within 15-mile service radius, businesses with 500–5,000 sq ft spaces",
            psychographics: "Value reliability above all, frustrated by previous cleaning services, need after-hours service that doesn't disrupt operations",
            buyingMotivations: ["Current cleaner is unreliable", "Moving into new office space", "Preparing for health/safety inspection", "Employee complaints about cleanliness"],
            serviceArea: "[Your City] commercial and business districts within 15 miles",
            revenueStreams: ["Monthly cleaning contracts ($200–$800/month)", "Deep cleaning services ($300–$1,000)", "Post-construction cleanup ($500–$2,000)", "Move-in/move-out cleaning ($200–$500)", "Add-on services (carpet, windows)"],
            upsells: ["Floor stripping and waxing", "Carpet cleaning quarterly", "Window cleaning", "Restroom supply management", "Day porter services"],
            pricingNotes: "Price per square foot: $0.05–$0.20/sq ft depending on frequency and scope. Monthly contracts with auto-billing. Deep cleans quoted individually.",
            startupCostItemsEssential: [("Commercial cleaning supplies", "$100–$300"), ("Vacuum (commercial grade)", "$200–$400"), ("Mop, bucket, and floor care", "$50–$100"), ("Cleaning caddy and chemicals", "$50–$100"), ("Liability insurance", "$500–$1,500/year")],
            startupCostItemsOptional: [("Floor buffer/scrubber", "$500–$2,000"), ("Vehicle lettering", "$200–$500"), ("Uniforms", "$100–$200"), ("Website", "$200–$500")],
            equipment: ["Commercial vacuum", "Mop and bucket system", "Spray bottles and microfiber cloths", "Trash bags and liners", "Floor buffer (for hard floors)"],
            tools: ["Extension duster", "Restroom cleaning kit", "Glass cleaner and squeegee", "Disinfectant sprayer", "Step ladder"],
            software: ["Swept or CleanGuru for job management", "QuickBooks or Wave for invoicing", "Google Business Profile"],
            vehicleNeeds: "Personal vehicle is sufficient initially. Hatchback or SUV for carrying supplies. No specialized vehicle needed.",
            workspaceNeeds: "Home-based. Store supplies in garage or closet. All work performed at client locations during after-hours.",
            legalStructureRecommendation: "LLC recommended once you have 3+ contracts. Protects personal assets and looks professional to commercial clients.",
            licensesAndPermits: ["Business license", "Some states require janitorial business registration"],
            insuranceNeeds: ["General liability ($1M)", "Bonding (commercial clients often require this)", "Workers compensation (when hiring)"],
            operationsDaily: ["Load supplies for evening route", "Travel to first location", "Complete cleaning per checklist", "Photo-document completed work", "Move to next location", "Restock supplies as needed"],
            schedulingWorkflow: "Set recurring weekly/biweekly schedules. Group clients geographically for efficient routes. After-hours cleaning (6pm–10pm typical).",
            customerWorkflow: "Business owner inquiry → site walkthrough → written proposal → trial cleaning → contract signed → recurring schedule → monthly invoice → quarterly review",
            followUpWorkflow: "Monthly check-in email to confirm satisfaction. Quarterly site walkthrough. Annual contract renewal with pricing review.",
            marketingChannels: ["Door-to-door visits to local businesses", "Google Business Profile", "LinkedIn outreach to business owners", "Facebook groups for local business owners", "Business networking events (BNI, chamber of commerce)"],
            acquisitionStrategies: ["Offer a free trial cleaning to win the first contract", "Visit businesses in person with a professional proposal", "Join local chamber of commerce and BNI groups", "Target businesses in the same building/complex as existing clients"],
            referralStrategies: ["One month free for referring a business that signs a contract", "Ask satisfied clients for introductions to other business owners", "Leave business cards with property managers"],
            partnershipIdeas: ["Property management companies (preferred vendor)", "Commercial real estate agents (referral to new tenants)", "Carpet cleaning companies (subcontract or cross-refer)", "Office supply companies (bundled services)"],
            socialProofStrategies: ["Client testimonial letters", "Before/after photos of deep cleans", "Bonded and insured messaging", "Client retention rate statistics"],
            salesProcess: ["Identify target businesses in your area", "Visit in person during business hours", "Request a walkthrough to quote accurately", "Present written proposal within 24 hours", "Offer free trial clean", "Follow up within 3 days"],
            salesTips: ["Visit businesses in person — email alone rarely works for cleaning", "The trial clean is your best sales tool", "Focus on reliability — it's the #1 complaint about cleaning services", "Ask what their current cleaner does wrong and promise to fix it"],
            objectionHandling: [("We already have a cleaner", "I hear that often. If you're ever unhappy with their work, I'd love to do a free trial clean so you can compare."), ("Too expensive", "Let me adjust the scope. We can start with the common areas and restrooms twice a week and expand from there.")],
            monthlyRevenueStarter: "$1,500–$3,000/month (3–5 contracts, evenings only)",
            monthlyRevenueModerate: "$5,000–$8,000/month (8–12 contracts, dedicated schedule)",
            monthlyRevenueStrong: "$12,000–$25,000+/month (multiple crews, 20+ contracts)",
            estimatedMonthlyExpensesStarter: "$300–$600 (supplies, gas, insurance)",
            estimatedMonthlyExpensesModerate: "$1,500–$3,000 (add labor, vehicle, marketing)",
            financialAssumptions: ["Average contract: $400–$600/month", "Supplies cost: 5–10% of revenue", "Labor (when hiring): 40–50% of contract value", "Target 50%+ margin on contracts you clean personally"],
            hiringPath: ["Solo for first 5–8 contracts", "Hire part-time cleaner for overflow", "Build a second crew for new route", "Quality inspector/manager at 15+ contracts"],
            scalingPath: ["Build to 10 contracts with solo/helper model", "Add second crew and route", "Target larger commercial spaces", "Offer specialty services (floor care, windows)"],
            expansionIdeas: ["Medical/dental office cleaning (premium pricing)", "Post-construction cleanup", "Floor care specialist services", "Day porter services for larger buildings"],
            riskFactors: ["Evening/weekend work schedule", "Employee turnover is high in cleaning industry", "Low margin per contract requires volume", "Key and alarm access creates trust/liability issues", "Price competition from larger janitorial companies"],
            difficultyNotes: "Very low barrier to entry. No special training required. Main challenge is sales and maintaining consistent quality as you scale.",
            viabilityNotes: "Commercial cleaning is recession-resistant — businesses always need clean spaces. Contracts provide predictable monthly revenue. Scales well with crews.",
            launchSteps30Days: ["Purchase basic commercial cleaning supplies", "Get business license and liability insurance", "Visit 20 local businesses with a one-page proposal", "Offer free trial cleans to 5 prospects", "Sign first 3 contracts", "Set up recurring schedule and invoicing"],
            launchSteps60Days: ["Grow to 5–8 contracts", "Optimize cleaning routes for efficiency", "Build quality checklists for each client", "Request testimonials from satisfied clients", "Join local business networking group"],
            launchSteps90Days: ["Evaluate if ready to hire first helper", "Reach 8–12 contracts", "Approach property management companies", "Add deep cleaning as upsell service", "Set revenue targets for next quarter"],
            fitSummary: "Commercial cleaning offers predictable recurring revenue with low startup costs. Contracts provide monthly stability. Scales well from solo operator to multi-crew operation.",
            bestFor: ["People who want reliable recurring monthly income", "Those comfortable with evening/weekend work schedules", "Entrepreneurs looking for a low-cost business with clear scaling path", "Anyone who values doing a thorough job and building client relationships"]
        ),

        BusinessPlanData(
            pathId: "car-detailing",
            mission: "Deliver showroom-quality mobile car detailing that saves customers time and keeps their vehicles looking new.",
            vision: "Build a premium mobile detailing brand with loyal customers, fleet contracts, and a team of trained detailers.",
            problemPoints: [
                "Car owners want clean vehicles but lack the time, equipment, or expertise for proper detailing.",
                "Traditional detail shops require dropping off the car for hours.",
                "Drive-through car washes can't match hand-detail quality."
            ],
            solutionPoints: [
                "Mobile service — detailing done at the customer's home or office while they work.",
                "Hand-wash and detail quality that drive-through washes can't match.",
                "Convenient online booking and recurring maintenance plans."
            ],
            primaryCustomer: "Car owners who value their vehicle's appearance and their own time",
            secondaryCustomer: "Car dealerships, fleet operators, and real estate agents (listing photos need clean cars)",
            demographics: "Vehicle owners aged 25-55, household income $50K+, professionals who commute daily",
            psychographics: "Convenience-driven, take pride in their vehicle, willing to pay for premium service that comes to them",
            buyingMotivations: ["Want a clean car without the hassle", "Preparing vehicle for sale or trade", "Seasonal deep clean", "Maintaining new vehicle condition"],
            serviceArea: "[Your City] homes and offices within 15 miles",
            revenueStreams: ["Interior detail ($75–$150)", "Exterior wash and wax ($80–$200)", "Full detail ($200–$400)", "Ceramic coating ($300–$800)", "Monthly maintenance plans ($80–$150/month)"],
            upsells: ["Ceramic coating application", "Paint correction and polishing", "Headlight restoration", "Engine bay cleaning", "Odor elimination treatment"],
            pricingNotes: "Price by vehicle size (sedan/SUV/truck). Offer packages: Basic, Premium, Ultimate. Monthly plans for recurring revenue. Fleet pricing at volume discount.",
            startupCostItemsEssential: [("Detailing supplies (soap, wax, microfibers)", "$150–$300"), ("Portable vacuum", "$100–$200"), ("Buckets, brushes, and applicators", "$50–$100"), ("Water source (tank or client hose)", "$0–$200"), ("Liability insurance", "$500–$1,000/year")],
            startupCostItemsOptional: [("Pressure washer", "$200–$500"), ("Ceramic coating kit", "$200–$500"), ("Polishing machine", "$150–$400"), ("Vehicle lettering", "$200–$500")],
            equipment: ["Dual-action polisher", "Portable wet/dry vacuum", "Foam cannon or pump sprayer", "Microfiber towel inventory (50+)", "Clay bar kit"],
            tools: ["Various brushes (wheel, interior, vent)", "Applicator pads", "Detailing spray bottles", "Tire shine applicators", "Steam cleaner (optional)"],
            software: ["Urable or Square Appointments for booking", "Instagram for portfolio", "Google Business Profile"],
            vehicleNeeds: "SUV, van, or truck to carry all supplies and equipment. Client hose hookup or carry a water tank.",
            workspaceNeeds: "Home-based. Store supplies in garage. All work done at client locations.",
            legalStructureRecommendation: "LLC optional initially, recommended once revenue exceeds $3,000/month. Protects against potential vehicle damage claims.",
            licensesAndPermits: ["Business license", "Check local water use regulations"],
            insuranceNeeds: ["General liability", "Garage keeper's liability (protects against vehicle damage claims)"],
            operationsDaily: ["Confirm appointments and check supplies", "Travel to first appointment", "Complete detail per package booked", "Take before/after photos", "Invoice and collect payment", "Post content on social media", "Travel to next appointment"],
            schedulingWorkflow: "Book 3–5 details per day depending on package. Route geographically. Offer recurring monthly slots to regular clients.",
            customerWorkflow: "Online/text booking → confirm appointment → arrive on time → complete detail → show customer results → invoice → request review → offer monthly plan",
            followUpWorkflow: "Before/after photos sent same day. Review request within 24 hours. Monthly maintenance reminder. Seasonal detail promotion.",
            marketingChannels: ["Instagram (before/after photos and reels)", "TikTok detailing videos", "Google Business Profile", "Nextdoor and local Facebook groups", "Vehicle signage"],
            acquisitionStrategies: ["Create satisfying before/after content for social media", "Offer first-detail discount to new customers", "Detail friends' and family's cars for initial portfolio", "Park at office buildings with a sign during lunch hour"],
            referralStrategies: ["$20 off next detail for every referral", "Business cards with referral code", "Tag customers in social media posts (with permission)"],
            partnershipIdeas: ["Car dealerships (overflow detail work)", "Auto body shops (post-repair details)", "Real estate agents (clean cars for showing homes)", "Office building management (employee perk program)"],
            socialProofStrategies: ["Before/after photo portfolio", "Video timelapses of the detailing process", "Google and Yelp reviews", "Customer testimonials"],
            salesProcess: ["Respond to inquiries within 30 minutes", "Recommend package based on vehicle condition", "Book within 3–5 days", "Arrive on time and exceed expectations", "Send before/after photos", "Offer monthly maintenance plan"],
            salesTips: ["Before/after photos are your #1 sales tool", "Upsell ceramic coating — it's high margin and impressive", "Offer a monthly plan at a slight discount for predictable revenue", "Social media content drives most new customers"],
            objectionHandling: [("I can wash it myself", "A hand wash is great for maintenance! But a professional detail addresses the things a wash can't — paint decontamination, interior deep clean, and protection. Think of it like the difference between brushing your teeth and a dental cleaning."), ("Too expensive", "I have a basic package starting at $75 that covers the essentials. Once you see the results, you can decide if you want to upgrade next time.")],
            monthlyRevenueStarter: "$2,000–$4,000/month (part-time, 8–12 details/week)",
            monthlyRevenueModerate: "$5,000–$8,000/month (full-time, 15–20 details/week)",
            monthlyRevenueStrong: "$10,000–$18,000+/month (with helper, fleet contracts, ceramic coatings)",
            estimatedMonthlyExpensesStarter: "$300–$600 (supplies, gas, insurance)",
            estimatedMonthlyExpensesModerate: "$800–$1,500 (add marketing, vehicle costs, products)",
            financialAssumptions: ["Average detail: $200–$300", "Product cost per detail: $10–$20", "Monthly plans average $120/month", "Ceramic coatings: $400–$700 with $50–$100 in product cost"],
            hiringPath: ["Solo for first 6 months", "Hire part-time helper for busy days", "Train helper to run second mobile unit", "Booking coordinator at 30+ details/week"],
            scalingPath: ["Build monthly plan subscriber base", "Add second mobile unit with trained detailer", "Add ceramic coating as premium service", "Pursue fleet and dealership contracts"],
            expansionIdeas: ["Ceramic coating and paint correction specialization", "Fleet detailing contracts", "Boat and RV detailing", "Detail training courses"],
            riskFactors: ["Weather dependent for exterior work", "Physical demands of detailed hand work", "Product investment for premium services", "Seasonal demand fluctuation", "Vehicle damage liability"],
            difficultyNotes: "Low barrier to entry. Learn techniques from YouTube and practice. Invest in quality products. Skills improve quickly with practice.",
            viabilityNotes: "Mobile detailing has strong demand driven by convenience. Social media marketing is extremely effective for this business. High margins on premium services.",
            launchSteps30Days: ["Purchase basic detailing supplies and equipment", "Detail 5 cars for friends/family — build before/after portfolio", "Create Instagram and Google Business Profile", "Post first before/after content", "Get first 5 paid clients through social media and Nextdoor", "Collect Google reviews from every client"],
            launchSteps60Days: ["Build to 10–15 details per week", "Launch monthly maintenance plan offering", "Create TikTok content for wider reach", "Connect with 2 local dealerships for overflow work", "Invest in ceramic coating supplies and training"],
            launchSteps90Days: ["Evaluate revenue and client retention", "Assess readiness for part-time helper", "Grow social media following to 500+", "Launch referral program", "Set pricing for premium ceramic coating services"],
            fitSummary: "Car detailing is one of the best low-investment service businesses. Mobile convenience drives demand. Social media marketing is highly effective. Clear path from solo operator to multi-unit operation.",
            bestFor: ["Detail-oriented people who enjoy making things look perfect", "Those who want to start earning quickly with low investment", "Social media savvy entrepreneurs", "Anyone who enjoys working outdoors and independently"]
        ),

        BusinessPlanData(
            pathId: "landscaping",
            mission: "Provide reliable, quality lawn care and landscaping services that keep properties looking their best year-round.",
            vision: "Build a landscaping company with recurring maintenance accounts, seasonal service add-ons, and a crew that delivers consistent quality.",
            problemPoints: [
                "Homeowners lack time and equipment for proper lawn maintenance.",
                "Finding a reliable landscaper who shows up consistently is a common frustration.",
                "Seasonal needs (spring cleanup, fall leaves, snow) create year-round maintenance demand."
            ],
            solutionPoints: [
                "Reliable weekly/biweekly service with consistent quality — same crew every visit.",
                "Seasonal services that keep properties maintained year-round.",
                "Simple pricing with monthly billing for recurring clients."
            ],
            primaryCustomer: "Homeowners who want maintained lawns without doing it themselves",
            secondaryCustomer: "HOAs, property managers, small commercial properties",
            demographics: "Homeowners aged 30-65, household income $50K+, within 10-mile service radius",
            psychographics: "Busy professionals, value curb appeal, frustrated by unreliable past services",
            buyingMotivations: ["Lack of time for lawn maintenance", "Physical inability to do yard work", "Want professional-looking property", "HOA compliance requirements"],
            serviceArea: "[Your City] neighborhoods within 10 miles (tight radius for route efficiency)",
            revenueStreams: ["Weekly mowing and trimming ($30–$60/visit)", "Monthly maintenance packages ($120–$250/month)", "Spring/fall cleanup ($150–$400)", "Mulching and planting ($200–$800)", "Snow removal (seasonal add-on)"],
            upsells: ["Mulching and garden bed maintenance", "Bush and hedge trimming", "Leaf removal and fall cleanup", "Aeration and overseeding", "Snow removal in winter months"],
            pricingNotes: "Price per property size. Small lawn: $30–$40/visit. Medium: $40–$55. Large: $55–$75. Monthly plans at 4 visits with slight discount. Always quote in person for accuracy.",
            startupCostItemsEssential: [("Commercial mower (push or zero-turn)", "$300–$3,000"), ("String trimmer", "$100–$300"), ("Leaf blower", "$100–$300"), ("Basic hand tools (rake, shovel, edger)", "$50–$150"), ("Trailer (if using riding mower)", "$500–$2,000")],
            startupCostItemsOptional: [("Zero-turn mower (for efficiency)", "$3,000–$6,000"), ("Truck lettering/magnets", "$200–$500"), ("Hedge trimmer", "$100–$300"), ("Website", "$200–$500")],
            equipment: ["Commercial lawn mower", "String trimmer/weed whacker", "Leaf blower", "Hedge trimmer", "Edger"],
            tools: ["Rake, shovel, wheelbarrow", "Pruning shears", "Measuring wheel", "Gas cans and spare parts", "Tarps for debris hauling"],
            software: ["Jobber or LawnPro for scheduling", "QuickBooks or Wave for invoicing", "Google Business Profile"],
            vehicleNeeds: "Pickup truck or SUV with trailer for mower and equipment. Essential for the business.",
            workspaceNeeds: "Home-based. Garage or shed for equipment storage. Consider enclosed trailer for mobile storage.",
            legalStructureRecommendation: "LLC recommended once you have 10+ regular clients. Protects personal assets from property damage or injury claims.",
            licensesAndPermits: ["Business license", "Pesticide applicator license (if offering weed control)", "Some HOAs require proof of insurance from vendors"],
            insuranceNeeds: ["General liability ($500K–$1M)", "Commercial auto if using dedicated work vehicle", "Workers compensation (when hiring)"],
            operationsDaily: ["Review route and confirm schedule", "Load equipment and fuel up", "Complete route of 6–10 properties per day", "Handle any customer requests or issues", "Invoice for completed work", "Plan next day's route"],
            schedulingWorkflow: "Fixed weekly routes by geography. Monday-Friday routes. Weather backup on Saturdays. Same day each week for each client.",
            customerWorkflow: "Inquiry → in-person quote → agree on service and pricing → add to weekly route → monthly invoicing → seasonal upsell offers → annual contract renewal",
            followUpWorkflow: "Monthly service summary. Seasonal upsell email (mulching, cleanup, snow). Annual pricing review. Immediate response to service concerns.",
            marketingChannels: ["Door-to-door in neighborhoods you already serve", "Nextdoor and Facebook local groups", "Google Business Profile", "Yard signs at properties you maintain", "Vehicle and trailer signage"],
            acquisitionStrategies: ["Knock on doors in the same neighborhood as current clients", "Offer first mow free to new clients on existing routes", "Post seasonal promotions on Nextdoor", "Place yard signs at every property you maintain"],
            referralStrategies: ["Free mow for every referral that signs up", "Leave flyers with neighboring properties", "Ask every client for one referral per season"],
            partnershipIdeas: ["Real estate agents (curb appeal for listings)", "Property managers (maintenance contracts)", "Irrigation companies (cross-referral)", "Tree services (jobs you can't handle)"],
            socialProofStrategies: ["Before/after photos of properties", "Consistent schedule reliability as selling point", "Google reviews mentioning dependability", "Year count of faithful service"],
            salesProcess: ["Quote in person by walking the property", "Present monthly plan vs. per-visit pricing", "Offer first mow free on existing route", "Add to route within one week", "Deliver consistent quality from day one", "Upsell seasonal services over time"],
            salesTips: ["Sell reliability — it's the #1 thing customers want", "Bundle seasonal services into annual plans for higher revenue", "Route density is key — the more clients per neighborhood, the more profitable", "Offer monthly billing for convenience (and your cash flow)"],
            objectionHandling: [("I do it myself", "I totally understand. If you ever want to free up your weekends, I'm right in the neighborhood and can take it off your plate for less than you'd think."), ("Too expensive", "I can adjust the service level. Basic mow and trim is my most affordable option and keeps your property looking great.")],
            monthlyRevenueStarter: "$2,000–$4,000/month (solo, 15–25 weekly accounts)",
            monthlyRevenueModerate: "$5,000–$8,000/month (solo with helper, 30–40 accounts)",
            monthlyRevenueStrong: "$12,000–$25,000+/month (2–3 crews, 60+ accounts plus commercial)",
            estimatedMonthlyExpensesStarter: "$500–$1,000 (gas, equipment maintenance, insurance)",
            estimatedMonthlyExpensesModerate: "$1,500–$3,000 (add labor, vehicle, marketing)",
            financialAssumptions: ["Average residential account: $150–$200/month", "6–10 properties per day per crew", "Equipment replacement: $1,000–$2,000/year", "Seasonal add-ons can double monthly revenue in peak months"],
            hiringPath: ["Solo for first season", "Hire part-time helper to increase daily capacity", "Build second crew for expanded route", "Crew leader/manager when running 3+ crews"],
            scalingPath: ["Build dense routes in 2–3 neighborhoods", "Add seasonal services for year-round revenue", "Hire and train a second crew", "Pursue HOA and commercial contracts"],
            expansionIdeas: ["Hardscaping and landscape design", "Irrigation installation and repair", "Snow removal (winter revenue)", "Tree and shrub care programs"],
            riskFactors: ["Seasonal revenue fluctuation (winter slowdown in cold climates)", "Weather delays and cancellations", "Equipment breakdown during peak season", "Labor reliability challenges", "Physical demands in heat and weather"],
            difficultyNotes: "Very low barrier to entry. Start with basic equipment. Physical work. Main challenge is building route density and managing growth.",
            viabilityNotes: "Lawn care is one of the most proven service business models. Recurring revenue, clear scaling path, and year-round potential with seasonal services.",
            launchSteps30Days: ["Purchase or tune up mowing equipment", "Mow 3–5 lawns for friends/family as practice", "Post on Nextdoor and Facebook groups", "Knock on 30 doors in target neighborhoods", "Sign up first 10 recurring clients", "Set up scheduling and invoicing system"],
            launchSteps60Days: ["Grow to 20+ weekly accounts", "Optimize routes for efficiency", "Add edge trimming and cleanup to every visit", "Request Google reviews from every client", "Price and promote seasonal services"],
            launchSteps90Days: ["Evaluate route profitability", "Assess need for part-time help", "Expand into adjacent neighborhoods", "Launch fall cleanup and leaf removal service", "Set revenue and client targets for next season"],
            fitSummary: "Landscaping and lawn care is one of the most proven, scalable service businesses. Low startup cost, recurring revenue, and clear path from solo operator to multi-crew company.",
            bestFor: ["People who enjoy outdoor physical work", "Those who want predictable recurring revenue", "Entrepreneurs looking for a proven, scalable business model", "Anyone who values independence and working on their own schedule"]
        ),

        BusinessPlanData(
            pathId: "mobile-barber",
            mission: "Bring professional barbering directly to clients' homes, offices, and care facilities with quality cuts and reliable scheduling.",
            vision: "Build a premium mobile barbering brand known for convenience, consistency, and expanding to multiple barbers serving the community.",
            problemPoints: [
                "Many people struggle to find time for barbershop visits during business hours.",
                "Elderly and mobility-limited individuals have difficulty getting to barber shops.",
                "Traditional barbershops often have long wait times and inconsistent quality."
            ],
            solutionPoints: [
                "Premium haircuts delivered at the client's location — home, office, or care facility.",
                "Scheduled appointments eliminate wait times.",
                "Consistent quality from the same barber every visit."
            ],
            primaryCustomer: "Working professionals who value convenience",
            secondaryCustomer: "Elderly clients, assisted living facilities, families wanting in-home cuts",
            demographics: "Men and boys aged 10-80, within 15-mile service radius, diverse income levels",
            psychographics: "Time-constrained, value convenience, willing to pay premium for at-home service, prefer personal relationship with their barber",
            buyingMotivations: ["No time for barbershop visits", "Mobility limitations", "Prefer private haircut experience", "Convenience for families with children"],
            serviceArea: "[Your City] homes, offices, and care facilities within 15 miles",
            revenueStreams: ["Individual haircuts ($35–$60)", "Haircut + beard trim ($45–$70)", "Group bookings at offices ($30–$40/cut for 5+)", "Assisted living facility contracts ($25–$35/cut, volume)", "Monthly subscription plans ($100–$150/month for 2 cuts)"],
            upsells: ["Beard trim and shaping", "Hot towel treatment", "Hair product sales", "Group office bookings", "Event cuts (wedding party, prom)"],
            pricingNotes: "Mobile premium of $10–$20 over shop rates. Volume discounts for facilities and offices. Monthly subscription plans for regular clients.",
            startupCostItemsEssential: [("Professional clippers (Wahl, Andis)", "$200–$400"), ("Trimmer set", "$100–$200"), ("Barber cape and accessories", "$50–$100"), ("Sanitization supplies", "$30–$50"), ("Barber license (if required by state)", "$100–$500")],
            startupCostItemsOptional: [("Portable barber chair", "$200–$500"), ("Product line for retail sales", "$100–$300"), ("Vehicle lettering", "$200–$500"), ("Booking app subscription", "$20–$50/month")],
            equipment: ["Professional clipper set", "Trimmer/edger", "Straight razor and guards", "Hot lather machine", "Portable mirror"],
            tools: ["Combs and brushes set", "Spray bottle", "Neck strips and powder", "Cleaning brush", "Blade oil and disinfectant"],
            software: ["Square Appointments or Booksy for scheduling", "Cash App/Venmo/Square for payments", "Instagram for portfolio"],
            vehicleNeeds: "Personal vehicle to travel between appointments. No special modifications needed — equipment fits in a bag.",
            workspaceNeeds: "No fixed workspace needed. All work done at client locations. Store supplies at home.",
            legalStructureRecommendation: "Sole proprietor is fine initially. LLC optional when revenue exceeds $3,000/month.",
            licensesAndPermits: ["Barber or cosmetology license (required in most states)", "Business license", "Health department registration (varies by state)"],
            insuranceNeeds: ["General liability", "Professional liability (malpractice for personal services)"],
            operationsDaily: ["Confirm day's appointments", "Sanitize and pack equipment", "Travel to clients (3–6 appointments per day)", "Complete haircuts", "Collect payment and book next appointment", "Post content on social media", "Clean and sanitize all tools"],
            schedulingWorkflow: "Online booking system with set time slots. Allow 45–60 minutes per appointment including travel. Group appointments geographically.",
            customerWorkflow: "Client books online or by text → confirmation sent → arrive on time → complete haircut → payment → book next appointment → review request",
            followUpWorkflow: "Reminder text 2–3 weeks after last cut. Monthly newsletter with grooming tips. Birthday discount for regulars.",
            marketingChannels: ["Instagram and TikTok (haircut videos and transformations)", "Word of mouth and referrals", "Nextdoor posts", "Flyers at gyms and barber supply stores", "Partnerships with assisted living facilities"],
            acquisitionStrategies: ["Post haircut transformation videos on social media", "Offer $10 off first mobile haircut", "Visit assisted living facilities to propose contract services", "Approach office buildings for corporate grooming days"],
            referralStrategies: ["$10 off for every referred new client", "Referral card program", "Tag clients in social media posts"],
            partnershipIdeas: ["Assisted living and nursing facilities", "Corporate offices (employee perk)", "Wedding planners (groomsmen packages)", "Gyms and athletic facilities"],
            socialProofStrategies: ["Haircut transformation photos and videos", "Client testimonials and reviews", "License and certification displayed", "Consistent social media presence"],
            salesProcess: ["Post content on social media consistently", "Respond to inquiries within 30 minutes", "Offer first-cut discount", "Deliver exceptional experience", "Book next appointment before leaving", "Request review and referral"],
            salesTips: ["Your best marketing is a great haircut — every client is a walking billboard", "Social media content drives most new clients", "Consistency builds loyalty — same time, same quality, every visit", "Upsell beard work and products during the appointment"],
            objectionHandling: [("I go to a regular barbershop", "Totally understand. The mobile experience saves you travel and wait time. Try it once — if you don't love the convenience, nothing lost."), ("Too expensive", "The mobile fee covers my travel to you. Factor in your own travel time and waiting room time, and it's a great value.")],
            monthlyRevenueStarter: "$2,000–$3,500/month (part-time, 3–4 cuts/day)",
            monthlyRevenueModerate: "$4,000–$7,000/month (full-time, 5–6 cuts/day)",
            monthlyRevenueStrong: "$8,000–$12,000+/month (with facility contracts, group bookings)",
            estimatedMonthlyExpensesStarter: "$200–$400 (gas, supplies, insurance, booking software)",
            estimatedMonthlyExpensesModerate: "$500–$800 (add marketing, products, vehicle costs)",
            financialAssumptions: ["Average cut: $40–$50", "4–6 cuts per day feasible", "Product sales: $100–$300/month additional", "Facility contracts: $500–$1,500/month recurring"],
            hiringPath: ["Solo for first year", "Train second barber for overflow and coverage", "Add barbers for high-demand areas", "Booking manager at 20+ appointments/day"],
            scalingPath: ["Build regular client base of 50+ recurring clients", "Secure 2–3 assisted living facility contracts", "Offer corporate grooming packages", "Train and deploy additional mobile barbers"],
            expansionIdeas: ["Assisted living and memory care facility contracts", "Corporate office grooming programs", "Event and wedding barbering packages", "Barbering education and mentorship"],
            riskFactors: ["Barber license required in most states", "Travel time between appointments limits daily capacity", "Physical demands of standing and cutting all day", "Client cancellations can disrupt schedule", "Weather can affect travel"],
            difficultyNotes: "Requires barber license which varies by state (6–18 months of schooling). Strong interpersonal skills needed. Physical work.",
            viabilityNotes: "Growing demand for convenience services. Mobile barbers command premium rates. Strong repeat business — everyone needs haircuts. Facility contracts provide stable recurring revenue.",
            launchSteps30Days: ["Verify barber license is current", "Purchase professional-grade equipment", "Set up online booking system", "Cut for 10 friends/family to build portfolio", "Create Instagram page with transformation photos", "Complete first 10 paid appointments"],
            launchSteps60Days: ["Build to 15+ regular clients", "Visit 3 assisted living facilities to propose services", "Post content 3x/week on social media", "Reach 10+ Google reviews", "Launch referral program"],
            launchSteps90Days: ["Evaluate route efficiency and daily capacity", "Secure first facility contract", "Assess demand for additional services", "Plan for corporate partnership outreach", "Set quarterly revenue targets"],
            fitSummary: "Mobile barbering combines skilled work with premium convenience pricing. Strong repeat business, low overhead, and clear paths to scale through facility contracts and team building.",
            bestFor: ["Licensed barbers seeking independence and premium pay", "Those who enjoy building personal client relationships", "People who value schedule flexibility", "Entrepreneurs interested in growing a service team"]
        )
    ]
}
