import SwiftUI

/// Renders a multi-page, letter-size Proof Portfolio PDF from the user's
/// profile, matches, milestones, and logged wins.
enum ProofPortfolioPDFService {

    private static let accent = Color(hex: "059669")
    private static let ink = Color(hex: "1A1A1E")
    private static let inkSecondary = Color(hex: "6E6E78")
    private static let inkTertiary = Color(hex: "9C9CA4")
    private static let line = Color(hex: "E5E5EA")

    private static let pageWidth: CGFloat = 612
    private static let pageHeight: CGFloat = 792

    // MARK: - Entry point

    static func export(appState: AppState) -> URL? {
        var pages: [AnyView] = []
        pages.append(AnyView(coverPage(appState: appState, pageNumber: pages.count + 1)))

        if appState.futurePlan != nil || appState.myPath != nil {
            pages.append(AnyView(planPage(appState: appState, pageNumber: pages.count + 1)))
        }

        let wins = appState.realWorldWins
        let chunks = stride(from: 0, to: wins.count, by: 9).map {
            Array(wins[$0..<min($0 + 9, wins.count)])
        }
        for chunk in chunks {
            pages.append(AnyView(winsPage(chunk: chunk, totalWins: wins.count,
                                          pageNumber: pages.count + 1)))
        }

        guard !pages.isEmpty else { return nil }

        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("Prooffd Proof Portfolio.pdf")

        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let data = renderer.pdfData { context in
            for page in pages {
                context.beginPage()
                let imageRenderer = ImageRenderer(content: page)
                imageRenderer.scale = 2
                if let image = imageRenderer.uiImage {
                    image.draw(in: pageRect)
                }
            }
        }

        do {
            try data.write(to: url)
            return url
        } catch {
            return nil
        }
    }

    // MARK: - Page Shell

    private struct PortfolioPage<Content: View>: View {
        let pageNumber: Int
        @ViewBuilder var content: Content

        var body: some View {
            VStack(alignment: .leading, spacing: 0) {
                content
                Spacer(minLength: 12)
                HStack {
                    Text("Generated by Prooffd")
                        .font(.caption2)
                        .foregroundStyle(inkTertiary)
                    Spacer()
                    Text("Page \(pageNumber)")
                        .font(.caption2)
                        .foregroundStyle(inkTertiary)
                }
            }
            .padding(48)
            .frame(width: pageWidth, height: pageHeight, alignment: .topLeading)
            .background(.white)
        }
    }

    // MARK: - Cover Page

    private static func coverPage(appState: AppState, pageNumber: Int) -> some View {
        let firstName = appState.userProfile.firstName.trimmingCharacters(in: .whitespaces)
        let displayName = firstName.isEmpty ? "Your" : firstName
        let pathTitle = appState.chosenPath?.title ?? appState.userProfile.derivedChosenPath.title
        let topMatches = appState.matchResults.prefix(5)
        let completedMilestones = appState.myPath?.milestones.filter(\.isCompleted).count ?? 0

        return PortfolioPage(pageNumber: pageNumber) {
            Rectangle()
                .fill(accent)
                .frame(height: 8)
                .frame(maxWidth: .infinity)
                .padding(-48)

            VStack(alignment: .leading, spacing: 6) {
                Text("PROOFFD")
                    .font(.system(size: 12, weight: .heavy))
                    .tracking(3)
                    .foregroundStyle(accent)
                Text("Proof Portfolio")
                    .font(.system(size: 32, weight: .bold))
                    .foregroundStyle(ink)
                Text("Prepared for \(displayName) • \(Date().formatted(.dateTime.month().day().year()))")
                    .font(.system(size: 13))
                    .foregroundStyle(inkSecondary)
            }
            .padding(.top, 28)

            Divider().overlay(line).padding(.vertical, 20)

            Text("Summary")
                .font(.system(size: 15, weight: .bold))
                .foregroundStyle(ink)

            VStack(spacing: 0) {
                summaryRow(label: "Chosen Path", value: pathTitle)
                summaryRow(label: "Top Match",
                           value: topMatches.first.map { "\($0.businessPath.name) — \($0.scorePercentage)%" } ?? "—")
                summaryRow(label: "Real-World Wins", value: "\(appState.realWorldWins.count)")
                summaryRow(label: "Milestones Completed", value: "\(completedMilestones)")
                summaryRow(label: "Current Streak", value: "\(appState.streakTracker.currentStreak) days")
                summaryRow(label: "Longest Streak", value: "\(appState.streakTracker.longestStreak) days")
            }
            .padding(.top, 12)

            if !topMatches.isEmpty {
                Divider().overlay(line).padding(.vertical, 20)

                Text("Top Matches")
                    .font(.system(size: 15, weight: .bold))
                    .foregroundStyle(ink)

                VStack(spacing: 10) {
                    ForEach(Array(topMatches)) { result in
                        HStack(spacing: 12) {
                            Image(systemName: result.businessPath.icon)
                                .font(.system(size: 14))
                                .foregroundStyle(accent)
                                .frame(width: 24)
                            Text(result.businessPath.name)
                                .font(.system(size: 13, weight: .medium))
                                .foregroundStyle(ink)
                            Spacer()
                            Text("\(result.scorePercentage)%")
                                .font(.system(size: 13, weight: .bold))
                                .foregroundStyle(accent)
                                .monospacedDigit()
                        }
                    }
                }
                .padding(.top, 12)
            }
        }
    }

    private static func summaryRow(label: String, value: String) -> some View {
        HStack {
            Text(label)
                .font(.system(size: 13))
                .foregroundStyle(inkSecondary)
            Spacer()
            Text(value)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(ink)
                .multilineTextAlignment(.trailing)
        }
        .padding(.vertical, 7)
        .overlay(alignment: .bottom) {
            Rectangle().fill(line).frame(height: 0.5)
        }
    }

    // MARK: - Plan Page

    private static func planPage(appState: AppState, pageNumber: Int) -> some View {
        PortfolioPage(pageNumber: pageNumber) {
            VStack(alignment: .leading, spacing: 6) {
                Text("My Future Plan")
                    .font(.system(size: 26, weight: .bold))
                    .foregroundStyle(ink)
                Text("Niche, roadmap, and progress")
                    .font(.system(size: 13))
                    .foregroundStyle(inkSecondary)
            }
            .padding(.top, 20)

            if let plan = appState.futurePlan {
                VStack(alignment: .leading, spacing: 10) {
                    HStack(spacing: 12) {
                        Image(systemName: plan.nicheIcon)
                            .font(.system(size: 20))
                            .foregroundStyle(accent)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(plan.nicheName)
                                .font(.system(size: 17, weight: .bold))
                                .foregroundStyle(ink)
                            Text("\(plan.nicheTypeLabel) • \(plan.confidence)% confident")
                                .font(.system(size: 12))
                                .foregroundStyle(inkSecondary)
                        }
                        Spacer()
                    }

                    ForEach(Array(plan.roadmap.enumerated()), id: \.offset) { _, stage in
                        VStack(alignment: .leading, spacing: 5) {
                            Text("\(stage.title) — \(stage.subtitle)")
                                .font(.system(size: 12, weight: .bold))
                                .foregroundStyle(accent)
                            ForEach(stage.milestones, id: \.self) { milestone in
                                Text("•  \(milestone)")
                                    .font(.system(size: 12))
                                    .foregroundStyle(inkSecondary)
                            }
                        }
                        .padding(.top, 4)
                    }
                }
                .padding(.top, 16)
            }

            if let myPath = appState.myPath {
                VStack(alignment: .leading, spacing: 10) {
                    Divider().overlay(line).padding(.vertical, 12)

                    Text("My Path: \(myPath.name)")
                        .font(.system(size: 15, weight: .bold))
                        .foregroundStyle(ink)

                    ForEach(myPath.milestones) { milestone in
                        HStack(alignment: .top, spacing: 10) {
                            Image(systemName: milestone.isCompleted ? "checkmark.circle.fill" : "circle")
                                .font(.system(size: 12))
                                .foregroundStyle(milestone.isCompleted ? accent : inkTertiary)
                                .padding(.top, 1)
                            Text(milestone.title)
                                .font(.system(size: 12))
                                .foregroundStyle(milestone.isCompleted ? ink : inkSecondary)
                            Spacer(minLength: 0)
                            if let date = milestone.dateCompleted {
                                Text(date.formatted(.dateTime.month(.abbreviated).day()))
                                    .font(.system(size: 10))
                                    .foregroundStyle(inkTertiary)
                            }
                        }
                        .padding(.vertical, 3)
                    }
                }
            }
        }
    }

    // MARK: - Wins Pages

    private static func winsPage(chunk: [RealWorldWin], totalWins: Int, pageNumber: Int) -> some View {
        PortfolioPage(pageNumber: pageNumber) {
            VStack(alignment: .leading, spacing: 6) {
                Text("Real-World Wins")
                    .font(.system(size: 26, weight: .bold))
                    .foregroundStyle(ink)
                Text("\(totalWins) logged win\(totalWins == 1 ? "" : "s")")
                    .font(.system(size: 13))
                    .foregroundStyle(inkSecondary)
            }
            .padding(.top, 20)

            VStack(spacing: 0) {
                ForEach(chunk) { win in
                    HStack(alignment: .top, spacing: 14) {
                        Image(systemName: WinType.allCases.first { $0.rawValue == win.title }?.icon ?? "star.fill")
                            .font(.system(size: 13))
                            .foregroundStyle(accent)
                            .frame(width: 26)

                        VStack(alignment: .leading, spacing: 3) {
                            Text(win.title)
                                .font(.system(size: 13, weight: .semibold))
                                .foregroundStyle(ink)
                            if !win.note.isEmpty {
                                Text(win.note)
                                    .font(.system(size: 11))
                                    .foregroundStyle(inkSecondary)
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                        }
                        Spacer(minLength: 0)
                        Text(win.date.formatted(.dateTime.month(.abbreviated).day().year()))
                            .font(.system(size: 10))
                            .foregroundStyle(inkTertiary)
                    }
                    .padding(.vertical, 10)
                    .overlay(alignment: .bottom) {
                        Rectangle().fill(line).frame(height: 0.5)
                    }
                }
            }
            .padding(.top, 14)
        }
    }
}
